Added configs for instance limitations
rathena/rathena pull request #3753
Opened 2018-12-15 15:09 UTC by Lemongrass3110

* **Addressed Issue(s)**: #1661

* **Server Mode**: Both

* **Description of Pull Request**: 
Adds configurations to prevent party, guild and clan modifications while an instance is running.
On officials party modifications are blocked now.

Thanks to @admkakaroto

Still misses some messages for custom scenarios(guilds and clans). Maybe @aleos89 can help me out on this.

2019-04-12 14:38 UTC, Badarosk0 commented
Could you upgrade to the new review of rAthena for testing? @Lemongrass3110

2019-04-13 00:37 UTC, Badarosk0 commented
It appears that it is not yet compatible with the current version of rAthena.
```
bool guild_has_permission( struct map_session_data* sd, enum e_guild_permission permission ){
	nullpo_retr( false, sd );

	**_int position = guild_getposition( sd );_**

	if( position < 0 ){
		return false;
	}

	return ( sd->guild->position[position].mode & permission ) != 0;
}
```

2019-05-24 14:51 UTC, Badarosk0 commented
Currently I can still use the /invite command even with the generated instance.
@Lemongrass3110

2020-06-06 06:08 UTC, Badarosk0 commented
Could you update this PR with the current version of rAthena?
@Lemongrass3110

2020-11-27 15:25 UTC, sader1992 commented
it would be nice if the block can be set via command script.
for example
`party_block(<party_id>,<true|false>)`
same for guild/clan
we can for the instance call the party block if the config is set
we also can use this system for things other then instances, where players loss the direct control on party/guild/clan, the party/guild/clan can only be edited by command scripts while the block is applied
also it might be a good idea to export it to sql , so incase of server reload (optional maybe?)
this will give the server owner the ultimate control over those things if he Choose to use it for other systems.

I wanted to make this kind of system however this PR is already exist , it would be much more efficient to apply it to this directly.
if not I would create it and open a new PR for review after this is merged.

2020-11-27 21:35 UTC, lighta commented on src/map/clif.cpp
> +	char name[NAME_LENGTH];
= {0}
It bug me so much all those uninatialized variable.

2020-11-27 21:43 UTC, lighta commented on src/map/guild.cpp
> +	struct map_session_data *tsd = map_id2sd(sd->guild_invite_account);
can this lookup be moved after "already in another guild" check ?
Since the another guild is not dependant.

2020-11-27 21:48 UTC, lighta commented on src/map/guild.cpp
> +	if( map_getmapflag( sd->bl.m, MF_GUILDLOCK ) || sd->bg_id ){
`if(sd->bg_id || map_getmapflag( sd->bl.m, MF_GUILDLOCK )`
would be faster, there is no full elevation in c++

2020-11-27 21:51 UTC, lighta commented on src/map/guild.cpp
> +	if( map_getmapflag( sd->bl.m, MF_GUILDLOCK ) ){
why isn't this before the `instance_destroy(g->instance_id);`

2020-11-27 21:54 UTC, lighta commented on src/map/party.cpp
> +	if( map_getmapflag( sd->bl.m, MF_PARTYLOCK ) ){
this could be move before `party_search`

2020-11-27 21:59 UTC, lighta commented on src/map/pc.hpp
> +		bool refuse_party;
I didn't saw the real usage of the var.
Can't this create false positive and refuse all subsequent party request ?

2020-11-27 22:00 UTC, lighta requested changes
1 regression spotted in `instance_destroy`
Various optimisation could be done in functions, the fastest check should be done on top.

2023-08-26 12:51 UTC, Badarosk0 commented
Could you please update this PR? This one is out of date with the src. Thanks

2024-06-05 13:47 UTC, Badarosk0 commented
When possible, could you update this PR?
If you use "Adventure's Agency Party" you can recruit another player from within the instance and there is no limitation for this system.
https://github.com/rathena/rathena/commit/39d5a02a3176875257ae8b59383fa7ff846e09a1
I believe you need to limit the entry of new players to the party if the instance is generated.

2024-06-05 15:49 UTC, admkakaroto commented
> When possible, could you update this PR please? If you use "Adventure's Agency Party" you can recruit another player from within the instance and there is no limitation for this system. [39d5a02](https://github.com/rathena/rathena/commit/39d5a02a3176875257ae8b59383fa7ff846e09a1) I believe you need to limit the entry of new players to the party if the instance is generated.

If add mapflag partylock not avoid this problem?

2024-06-05 20:01 UTC, Badarosk0 commented
> > When possible, could you update this PR please? If you use "Adventure's Agency Party" you can recruit another player from within the instance and there is no limitation for this system. [39d5a02](https://github.com/rathena/rathena/commit/39d5a02a3176875257ae8b59383fa7ff846e09a1) I believe you need to limit the entry of new players to the party if the instance is generated.
> 
> If add mapflag partylock not avoid this problem?

Yes, adding it to src will partially resolve it. but the mapflag is inside the instance, so in the pre-map when the instance is generated, it will still be possible to recruit players with the generated instance

2024-06-12 20:51 UTC, Lemongrass3110 commented
```
on standby/inside instance:
can't invite (메모리얼 던전 이용 중엔 초대 및 탈퇴가 되지 않습니다 => MSI_CANNOT_JOIN_AND_LEAVE_PARTY_IN_MAKING_MEMORIALDUNGEON)
can't leave as both member and leader (메모리얼 던전 이용 중엔 초대 및 탈퇴가 되지 않습니다 => MSI_CANNOT_JOIN_AND_LEAVE_PARTY_IN_MAKING_MEMORIALDUNGEON)
can't expel (no message)
can't change leader (no message)
```

2024-06-12 21:30 UTC, aleos89 approved these changes

2024-06-12 21:36 UTC, merged