Correct up item db 27 apr 2020
rathena/rathena pull request #4877
Opened 2020-05-01 07:01 UTC by kaninhot004

* **Addressed Issue(s)**: 

-

* **Server Mode**: 

Renewal

* **Description of Pull Request**: 

Item DB & Item Combo DB updates.
Follow by lastest item info from kRO and Divine Pride with kRO server selected. (Some missing from jRO because it's not had on kRO)

Item DB

> 1322 - Correct up bonus and item data (https://www.divine-pride.net/database/item/1322/)
> 1336 - Added missing skill damage bonus (https://www.divine-pride.net/database/item/1336/)
> 1424 - Added missing large size damage bonus (https://www.divine-pride.net/database/item/1424/)
> 1426 - Added missing aspd rate bonus (https://www.divine-pride.net/database/item/1426/)
> 1435 - Changed atk bonus to skill damage bonus (https://www.divine-pride.net/database/item/1435/)
> 1437 - Adjusted curse rates (https://www.divine-pride.net/database/item/1437/)
> 1441 - Correct up bonus and item data (https://www.divine-pride.net/database/item/1441/)
> 1443 - Seperated atk bonus from new condition info (https://www.divine-pride.net/database/item/1443/)
> 1445 - Implemented missing items (https://www.divine-pride.net/database/item/1445/)
> 1448 - Implemented missing items (https://www.divine-pride.net/database/item/1448/)
> 1466 - Changed critical to critical rates (https://www.divine-pride.net/database/item/1466/)
> 1470 - Removed boss damage bonus (https://www.divine-pride.net/database/item/1470/)
> 1476 - Changed critical to critical rates (https://www.divine-pride.net/database/item/1476/)
> 1488 - Adjusted damage rates (https://www.divine-pride.net/database/item/1488/)
> 1489 - Removed unbreakable bonus (https://www.divine-pride.net/database/item/1489/)
> 1492 - Seperated magic damage return bonus from new condition info (https://www.divine-pride.net/database/item/1492/)
> 1494 - Added missing max hp rates bonus (https://www.divine-pride.net/database/item/1494/)
> 1495 - Adjusted blind rates (https://www.divine-pride.net/database/item/1495/)
> 1497 - Adjusted auto apwll skill level bonus (https://www.divine-pride.net/database/item/1497/)
> 1498 - Seperated atk bonus from new condition info (https://www.divine-pride.net/database/item/1498/)
> 1523 - Changed critical to critical rate and adjusted def decrease rates (https://www.divine-pride.net/database/item/1523/)
> 1541 - Changed race undead to element dark damage bonus (https://www.divine-pride.net/database/item/1541/)
> 1548 - Changed critical to critical rate bonus (https://www.divine-pride.net/database/item/1548/)
> 1567 - Remove mAtkRate bonus (https://www.divine-pride.net/database/item/1567/)
> 1573 - Added missing item bonus (https://www.divine-pride.net/database/item/1573/)
> 1574 - Correct up bonus and item data (https://www.divine-pride.net/database/item/1574/)
> 1575 - Correct up bonus (https://www.divine-pride.net/database/item/1575/)
> 1576 - Correct up bonus (https://www.divine-pride.net/database/item/1576/)
> 1577 - Correct up bonus (https://www.divine-pride.net/database/item/1577/)
> 1578 - Adjusted mDef bonus (https://www.divine-pride.net/database/item/1578/)
> 1580 - Removed mAtkRate bonus (https://www.divine-pride.net/database/item/1580/)
> 1585 - Change mAtk to atk bonus (https://www.divine-pride.net/database/item/1585/)
> 1586 - Correct up bonus (https://www.divine-pride.net/database/item/1586/)
> 1588 - Removed unbreakable bonus (https://www.divine-pride.net/database/item/1588/)
> 1590 - Added missing item bonus (https://www.divine-pride.net/database/item/1590/)
> 1591 - Change recovery bonus to heal power bonus (https://www.divine-pride.net/database/item/1591/)
> 1592 - Implemented missing items (https://www.divine-pride.net/database/item/1592/)
> 1593 - Implemented missing items (https://www.divine-pride.net/database/item/1593/)
> 1594 - Implemented missing items (https://www.divine-pride.net/database/item/1594/)
> 1595 - Implemented missing items (https://www.divine-pride.net/database/item/1595/)
> 1596 - Added missing int bonus (https://www.divine-pride.net/database/item/1596/)
> 1597 - Adjusted str bonus and remove unbreakble bonus (https://www.divine-pride.net/database/item/1597/)
> 1598 - Implemented missing items (https://www.divine-pride.net/database/item/1598/)
> 1599 - Added missing aspd rate bonus (https://www.divine-pride.net/database/item/1599/)
> 1664 - Added missing ignore mDefRate bonus (https://www.divine-pride.net/database/item/1664/)
> 1698 - Adjusted jobs req. (https://www.divine-pride.net/database/item/1698/)
> 29176 - Implemented missing items (https://www.divine-pride.net/database/item/29176/)
> 32234 - Implemented missing items (https://www.divine-pride.net/database/item/32234/)

Item Combo DB

> - RWC Staff, RWC Pendent, Chamber RWC Pendate use mAtk instead of mAtkRate
> - Added Snake Encyclopedia combo
> - Added Warrior's combo

Thanks to 🅺🅸🅽🅶🅰🆁🆃🅴🆁 # 4210 (Discord)

2020-06-21 08:35 UTC, kaninhot004 commented
Today I had more update. (Follow kRO description in Divine Pride)

2020-06-26 17:07 UTC, Atemo commented
Anything left? If the work is still in progress, change the PR to draft

2020-06-27 03:40 UTC, kaninhot004 commented
> Anything left? If the work is still in progress, change the PR to draft

It's done now. Thanks!

By the way next time I will keep it on draft, If still updating.

2020-10-08 08:33 UTC, KingarteR commented
please check and merge to master

2020-10-09 00:02 UTC, Atemo requested changes

2020-10-09 00:02 UTC, Atemo commented on db/re/item_db.txt
> +28566,Beginner's_Ring,Beginner's Ring,4,20,,0,,0,,0,0xFFFFFFFF,63,2,128,,100,0,0,{ bonus bAspdRate,10; bonus bVariableCast,10; },{},{}
```suggestion
28566,Beginner's_Ring,Beginner's Ring,4,20,,0,,0,,0,0xFFFFFFFF,63,2,128,,100,0,0,{ bonus bAspdRate,10; bonus bVariableCastrate,-10; },{},{}
```

2020-10-09 13:25 UTC, kaninhot004 commented on db/re/item_db.txt
> +1597,Half_BF_Book2,Half BF Book2,5,20,,0,90:125,,1,0,0x00210100,63,2,2,3,80,1,15,{ bonus bStr,1; bonus bInt,1; bonus2 bAddRace,RC_DemiHuman,35; bonus2 bAddRace,RC_Player_Human,35; bonus2 bIgnoreMdefR
From Divine Pride
![image](https://user-images.githubusercontent.com/9493525/95588411-960bc980-0a6d-11eb-8b92-45da611009ab.png)

2020-10-09 13:37 UTC, kaninhot004 commented
All changes is done. Thank you!

2020-10-09 13:53 UTC, Atemo commented on db/re/item_db.txt
> +1597,Half_BF_Book2,Half BF Book2,5,20,,0,90:125,,1,0,0x00210100,63,2,2,3,80,1,15,{ bonus bStr,1; bonus bInt,1; bonus2 bAddRace,RC_DemiHuman,35; bonus2 bAddRace,RC_Player_Human,35; bonus2 bIgnoreMdefR
I mean I can't find 1597 on DP or aegis, where did you get it ?

2020-10-09 14:15 UTC, Atemo commented
My comment were lost in the review, I can't find 1597 on DP or aegis, where did you get it ?

2020-10-10 02:29 UTC, kaninhot004 commented
> My comment were lost in the review, I can't find 1597 on DP or aegis, where did you get it ?

I selected kRO server on DP and it's show up.
https://www.divine-pride.net/database/item/1594

2020-10-10 20:55 UTC, Atemo commented
Alright, we can keep it it's fine!

2020-10-10 20:59 UTC, merged

2020-10-10 20:59 UTC, Atemo commented
Thanks!