item_db and item_combo_db correction #7
rathena/rathena pull request #5296
Opened 2020-08-06 14:02 UTC by kaninhot004

* **Server Mode**: 

Renewal

* **Description of Pull Request**: 

More of item_db and item_combo_db corrections.

https://www.divine-pride.net/database/item/28551/
https://www.divine-pride.net/database/item/28372/
https://www.divine-pride.net/database/item/1837/
https://www.divine-pride.net/database/item/15040/
https://www.divine-pride.net/database/item/18676/
https://www.divine-pride.net/database/item/22042/
https://www.divine-pride.net/database/item/13088/
https://www.divine-pride.net/database/item/28372/
https://www.divine-pride.net/database/item/18864/
https://www.divine-pride.net/database/item/18934/
https://www.divine-pride.net/database/item/18938/
https://www.divine-pride.net/database/item/28602/
https://www.divine-pride.net/database/item/2196/
https://www.divine-pride.net/database/item/28342/
https://www.divine-pride.net/database/item/2597/
https://www.divine-pride.net/database/item/19031/
https://www.divine-pride.net/database/item/22064/
https://www.divine-pride.net/database/item/2124/
https://www.divine-pride.net/database/item/2702/
https://www.divine-pride.net/database/item/15145/
https://www.divine-pride.net/database/item/18652/
https://www.divine-pride.net/database/item/19048/
https://www.divine-pride.net/database/item/19019/

Thanks to Jumbo # 8053 (Discord)

2020-09-08 19:25 UTC, crazy-arashi requested changes

2020-09-09 12:27 UTC, kaninhot004 commented on db/re/item_combo_db.txt
> +18823:28372,{ bonus2 bSkillVariableCast,"CR_GRANDCROSS",-2000; bonus2 bSkillAtk,"LG_RAYOFGENESIS",BaseLevel/30; bonus2 bSkillUseSP,"LG_RAYOFGENESIS",-10; bonus2 bSkillAtk,"CR_GRANDCROSS",BaseLevel; }
![image](https://user-images.githubusercontent.com/9493525/92597833-240b5d80-f2d2-11ea-9c6b-570f56fa4add.png)
In Divine Pride I had selected kRO servers, And translated item description by Google it said -2 seconds.

Do you had any description for this? Thanks!

2020-09-09 12:31 UTC, kaninhot004 commented on db/re/item_combo_db.txt
> +18823:28551,{ bonus bLongAtkRate,getskilllv("LG_CANNONSPEAR")*2; bonus bLongAtkRate,getskilllv("LG_OVERBRAND")*2; bonus2 bSkillAtk,"LG_CANNONSPEAR",20; bonus2 bSkillAtk,"LG_OVERBRAND",20; }
This is from Divine Pride kRO server selected, Please check it for me again.
If I wrong I will use your changes. Thanks!

![image](https://user-images.githubusercontent.com/9493525/92598342-db07d900-f2d2-11ea-9e9a-a9d836efc505.png)

2020-09-09 12:32 UTC, kaninhot004 commented on db/re/item_db.txt
> +1837,Iron_nail,Iron Nail,5,10,,1500,100,,,1,0x00008100,63,2,2,3,50,1,12,{ bonus bIgnoreDefClass,Class_All; .@r = (getrefine()/2); bonus bAspdRate,-5+.@r; if(getskilllv("MO_CHAINCOMBO")==5){ bonus bBa
There are no description about Unbreakable Weapon, Please help me check it again. Thanks!

![image](https://user-images.githubusercontent.com/9493525/92598552-291cdc80-f2d3-11ea-8fd1-24966e613b67.png)

2020-09-09 12:50 UTC, Atemo commented on db/re/item_db.txt
> +1837,Iron_nail,Iron Nail,5,10,,1500,100,,,1,0x00008100,63,2,2,3,50,1,12,{ bonus bIgnoreDefClass,Class_All; .@r = (getrefine()/2); bonus bAspdRate,-5+.@r; if(getskilllv("MO_CHAINCOMBO")==5){ bonus bBa
Select jRO server, some items can't be found in the itemInfo lua Korean
`絶対に壊れない ` (never break) in 1837 description

2020-09-09 12:54 UTC, saya9200 commented
I really appreciate the item additions @kaninhot004 , I've been looking for some of them!

2020-09-09 17:29 UTC, crazy-arashi approved these changes

2020-09-28 13:35 UTC, zdurexz commented
@Atemo Please check

2020-10-02 16:28 UTC, Atemo requested changes

2020-10-02 16:28 UTC, Atemo commented on db/re/item_db.txt
> +18934,Fox_Ears_Bell_Ribbon,Fox Ears Bell Ribbon,4,0,,400,,4,,1,0xFFFFFFFF,63,2,256,,50,1,1070,{ bonus bAgi,2; bonus bAspdRate,10; .@r = getrefine(); autobonus "{ .@i = .@r-6; bonus bCritical,100; bon
The string in autobonus is read independently of the item script, `getrefine()` must be redefined inside
```suggestion
18934,Fox_Ears_Bell_Ribbon,Fox Ears Bell Ribbon,4,0,,400,,4,,1,0xFFFFFFFF,63,2,256,,50,1,1070,{ bonus bAgi,2; bonus bAspdRate,10; .@r = getrefine(); autobonus "{ bonus bCritical,100; bonus bLongAtkRate,5+max(0,getrefine()-6); }",50+(.@r*2),5000,BF_NORMAL,"{ active_transform 1150,5000; }"; },{},{}
```

2020-10-03 03:43 UTC, kaninhot004 commented
All changes are done. Thank you!

2020-10-03 13:07 UTC, Atemo approved these changes

2020-10-03 13:08 UTC, merged

2020-10-03 13:08 UTC, Atemo commented
Thanks !