item_db and item_combo_db correction #8
rathena/rathena pull request #5332
Opened 2020-08-16 06:09 UTC by kaninhot004

* **Server Mode**: 

Renewal

* **Description of Pull Request**: 

More of item_db and item_combo_db corrections.

https://www.divine-pride.net/database/item/5920
https://www.divine-pride.net/database/item/2166
https://www.divine-pride.net/database/item/1691
https://www.divine-pride.net/database/item/19021
https://www.divine-pride.net/database/item/22106
https://www.divine-pride.net/database/item/22106
https://www.divine-pride.net/database/item/15169
https://www.divine-pride.net/database/item/15169
https://www.divine-pride.net/database/item/5966
https://www.divine-pride.net/database/item/5966
https://www.divine-pride.net/database/item/5966
https://www.divine-pride.net/database/item/13300
https://www.divine-pride.net/database/item/13301
https://www.divine-pride.net/database/item/13302
https://www.divine-pride.net/database/item/13303
https://www.divine-pride.net/database/item/13304
https://www.divine-pride.net/database/item/13307
https://www.divine-pride.net/database/item/13308
https://www.divine-pride.net/database/item/13309
https://www.divine-pride.net/database/item/13315
https://www.divine-pride.net/database/item/13316
https://www.divine-pride.net/database/item/13317
https://www.divine-pride.net/database/item/13322
https://www.divine-pride.net/database/item/13323
https://www.divine-pride.net/database/item/13327
https://www.divine-pride.net/database/item/13328
https://www.divine-pride.net/database/item/13332
https://www.divine-pride.net/database/item/13403
https://www.divine-pride.net/database/item/13411
https://www.divine-pride.net/database/item/13412
https://www.divine-pride.net/database/item/13413
https://www.divine-pride.net/database/item/13417
https://www.divine-pride.net/database/item/13418
https://www.divine-pride.net/database/item/13419
https://www.divine-pride.net/database/item/100273
https://www.divine-pride.net/database/item/100274
https://www.divine-pride.net/database/item/100275
https://www.divine-pride.net/database/item/100276
https://www.divine-pride.net/database/item/100277
https://www.divine-pride.net/database/item/100327
https://www.divine-pride.net/database/item/100328
https://www.divine-pride.net/database/item/100329
https://www.divine-pride.net/database/item/100330
https://www.divine-pride.net/database/item/100331
https://www.divine-pride.net/database/item/100360
https://www.divine-pride.net/database/item/100361
https://www.divine-pride.net/database/item/100362
https://www.divine-pride.net/database/item/100363
https://www.divine-pride.net/database/item/100376
https://www.divine-pride.net/database/item/100377
https://www.divine-pride.net/database/item/100378
https://www.divine-pride.net/database/item/100379
https://www.divine-pride.net/database/item/100388
https://www.divine-pride.net/database/item/100390
https://www.divine-pride.net/database/item/100393
https://www.divine-pride.net/database/item/100394
https://www.divine-pride.net/database/item/100395
https://www.divine-pride.net/database/item/100396
https://www.divine-pride.net/database/item/100397
https://www.divine-pride.net/database/item/100398
https://www.divine-pride.net/database/item/100399
https://www.divine-pride.net/database/item/100400
https://www.divine-pride.net/database/item/100401
https://www.divine-pride.net/database/item/100437
https://www.divine-pride.net/database/item/22238

2020-09-11 22:41 UTC, crazy-arashi requested changes

2020-09-11 22:41 UTC, crazy-arashi commented on db/re/item_db.txt
> +15169,Kardui_Robe,Kardui Robe,4,20,,800,,60,,1,0xFFFFFFFF,63,2,16,,90,1,0,{ bonus bMatk,10; bonus bMdef,5; bonus2 bSubRace,RC_DemiHuman,1; bonus2 bSubRace,RC_Player_Human,1; if(getrefine()>=7) { bonu
```suggestion
15169,Kardui_Robe,Kardui Robe,4,20,,800,,60,,1,0xFFFFFFFF,63,2,16,,90,1,0,{ bonus bMatk,10; bonus bMdef,5; bonus2 bSubRace,RC_DemiHuman,1; bonus2 bSubRace,RC_Player_Human,1; if(getrefine()>=7) { bonus2 bSubRace,RC_DemiHuman,2; bonus2 bSubRace,RC_Player_Human,2; } if(getrefine()>=8) { bonus2 bSubRace,RC_DemiHuman,2; bonus2 bSubRace,RC_Player_Human,2; bonus bUnbreakableArmor,1; } if(getrefine()>=9) { bonus2 bSubRace,RC_DemiHuman,2; bonus2 bSubRace,RC_Player_Human,2; } },{},{}
```

2020-09-11 22:41 UTC, crazy-arashi commented on db/re/item_db.txt
> +22238,Great_Hero_Boots,Great Hero Boots,4,20,,600,,15,,1,0xFFFFFFFF,63,2,64,,150,1,0,{ .@r = getrefine(); bonus bMaxHP,1500; bonus bMaxSP,150; bonus bMaxHPrate,.@r/3; bonus bMaxSPrate,.@r/3; if (.@r
```suggestion
22238,Great_Hero_Boots,Great Hero Boots,4,20,,600,,15,,1,0xFFFFFFFF,63,2,64,,150,1,,{ .@r = getrefine(); bonus bMaxHP,1500; bonus bMaxSP,150; bonus bMaxHPrate,.@r/3; bonus bMaxSPrate,.@r/3; if (.@r >= 7) { bonus2 bAddClass,Class_All,5; bonus bMatkRate,5; } if (.@r >= 9) { .@val = -500; if (.@r >= 11) { .@val -= 200; if (.@r >= 13) { bonus bDelayRate,-5; bonus bVariableCastrate,-5; } } bonus bFixedCast,.@val; } },{},{}
```

2020-09-12 02:45 UTC, kaninhot004 commented
Thank you @crazy-arashi .
All changes is done.

2020-09-12 06:49 UTC, crazy-arashi approved these changes

2020-09-26 14:05 UTC, Atemo approved these changes

2020-09-26 15:00 UTC, aleos89 approved these changes

2020-09-26 17:07 UTC, merged