Adds Advanced Potion Merchant NPC
rathena/rathena pull request #5360
Opened 2020-08-25 16:05 UTC by aleos89

* **Addressed Issue(s)**: N/A

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Adds the Advanced Potion Merchant who sells the Red, Yellow, White, and Blue Syrups for Concentrated Red Syrup Potion, Concentrated Blue Syrup Potion, and Concentrated Golden Syrup Potion creation.

2020-08-26 12:08 UTC, Latiosu approved these changes

2020-08-27 12:50 UTC, Atemo reviewed
The coordinates are taken from playing?

2020-08-27 12:51 UTC, attackjom commented
iirc there are co-ordinate of this NPC in navigation files.

2020-08-27 13:15 UTC, Atemo requested changes
Ref for the npcs directions/coordinates https://github.com/rathena/rathena/issues/3681#issuecomment-459234254
I also checked the npcs coordinates on kro navi (april 2020)

2020-08-27 13:15 UTC, Atemo commented on npc/re/merchants/shops.txt
> +aldeba_in,99,55,3	shop	Advanced Potion Merchant#alde	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```suggestion
aldeba_in,99,56,5	shop	Advanced Potion Merchant#alde	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```

2020-08-27 13:15 UTC, Atemo commented on npc/re/merchants/shops.txt
> +alberta_in,176,97,3	shop	Advanced Potion Merchant#alb	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```suggestion
alberta_in,176,97,5	shop	Advanced Potion Merchant#alb	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```

2020-08-27 13:15 UTC, Atemo commented on npc/re/merchants/shops.txt
> +geffen_in,78,169,5	shop	Advanced Potion Merchant#gef	1_F_03,11621:-1,11622:-1,11623:-1,11624:-1
```suggestion
geffen_in,78,169,3	shop	Advanced Potion Merchant#gef	1_F_03,11621:-1,11622:-1,11623:-1,11624:-1
```

2020-08-27 13:15 UTC, Atemo commented on npc/re/merchants/shops.txt
> +izlude_in,59,113,3	shop	Advanced Potion Merchant#iz	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```suggestion
izlude_in,59,113,5	shop	Advanced Potion Merchant#iz	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```

2020-08-27 13:15 UTC, Atemo commented on npc/re/merchants/shops.txt
> +morocc,170,84,7	shop	Advanced Potion Merchant#moc	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```suggestion
morocc,149,245,7	shop	Advanced Potion Merchant#moc1	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
morocc,170,84,1	shop	Advanced Potion Merchant#moc2	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```

2020-08-27 13:15 UTC, Atemo commented on npc/re/merchants/shops.txt
> +payon,157,96,5	shop	Advanced Potion Merchant#pay	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```suggestion
payon,157,96,3	shop	Advanced Potion Merchant#pay	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
payon_in01,12,53,5	shop	Advanced Potion Merchant#pay2	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
payon_in02,85,38,3	shop	Advanced Potion Merchant#pay3	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```

2020-08-27 13:15 UTC, Atemo commented on npc/re/merchants/shops.txt
> +prt_in,128,69,5	shop	Advanced Potion Merchant#prt	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```suggestion
prt_in,129,68,3	shop	Advanced Potion Merchant#prt	4_F_ALCHE_A,11621:-1,11622:-1,11623:-1,11624:-1
```

2020-08-27 14:02 UTC, aleos89 commented
Ah, I didn't realize we had an issue open for them. I was running around cities on kRO to find them.

2020-08-27 15:53 UTC, Atemo approved these changes

2020-08-27 18:04 UTC, merged