item_db and item_combo_db correction #9
rathena/rathena pull request #5374
Opened 2020-09-04 06:34 UTC by kaninhot004

* **Server Mode**: 

Renewal

* **Description of Pull Request**: 

item_db and item_combo_db update from reading Divine Pride (kRO server selected).

https://www.divine-pride.net/database/item/5920
https://www.divine-pride.net/database/item/2166
https://www.divine-pride.net/database/item/1691
https://www.divine-pride.net/database/item/19021
https://www.divine-pride.net/database/item/22106
https://www.divine-pride.net/database/item/22106
https://www.divine-pride.net/database/item/15169
https://www.divine-pride.net/database/item/15169
https://www.divine-pride.net/database/item/5966
https://www.divine-pride.net/database/item/5966
https://www.divine-pride.net/database/item/5966
https://www.divine-pride.net/database/item/13300
https://www.divine-pride.net/database/item/13301
https://www.divine-pride.net/database/item/13302
https://www.divine-pride.net/database/item/13303
https://www.divine-pride.net/database/item/13304
https://www.divine-pride.net/database/item/13307
https://www.divine-pride.net/database/item/13308
https://www.divine-pride.net/database/item/13309
https://www.divine-pride.net/database/item/13315
https://www.divine-pride.net/database/item/13316
https://www.divine-pride.net/database/item/13317
https://www.divine-pride.net/database/item/13322
https://www.divine-pride.net/database/item/13323
https://www.divine-pride.net/database/item/13327
https://www.divine-pride.net/database/item/13328
https://www.divine-pride.net/database/item/13332
https://www.divine-pride.net/database/item/13403
https://www.divine-pride.net/database/item/13411
https://www.divine-pride.net/database/item/13412
https://www.divine-pride.net/database/item/13413
https://www.divine-pride.net/database/item/13417
https://www.divine-pride.net/database/item/13418
https://www.divine-pride.net/database/item/13419
https://www.divine-pride.net/database/item/100273
https://www.divine-pride.net/database/item/100274
https://www.divine-pride.net/database/item/100275
https://www.divine-pride.net/database/item/100276
https://www.divine-pride.net/database/item/100277
https://www.divine-pride.net/database/item/100327
https://www.divine-pride.net/database/item/100328
https://www.divine-pride.net/database/item/100329
https://www.divine-pride.net/database/item/100330
https://www.divine-pride.net/database/item/100331
https://www.divine-pride.net/database/item/100360
https://www.divine-pride.net/database/item/100361
https://www.divine-pride.net/database/item/100362
https://www.divine-pride.net/database/item/100363
https://www.divine-pride.net/database/item/100376
https://www.divine-pride.net/database/item/100377
https://www.divine-pride.net/database/item/100378
https://www.divine-pride.net/database/item/100379
https://www.divine-pride.net/database/item/100388
https://www.divine-pride.net/database/item/100390
https://www.divine-pride.net/database/item/100393
https://www.divine-pride.net/database/item/100394
https://www.divine-pride.net/database/item/100395
https://www.divine-pride.net/database/item/100396
https://www.divine-pride.net/database/item/100397
https://www.divine-pride.net/database/item/100398
https://www.divine-pride.net/database/item/100399
https://www.divine-pride.net/database/item/100400
https://www.divine-pride.net/database/item/100401
https://www.divine-pride.net/database/item/100437
https://www.divine-pride.net/database/item/22238

2020-09-12 02:38 UTC, crazy-arashi requested changes

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +640004,Blue_Crystal_Staff,Blue Crystal Staff,5,,,800,100:200,,1,2,0x00000200,56,2,2,4,100,1,10,{ bonus bUnbreakableWeapon; .@r = getrefine(); bonus bMatk,.@r/2*10; bonus2 bSkillAtk,"WL_JACKFROST",.@r
```suggestion
640004,Blue_Crystal_Staff,Blue Crystal Staff,5,,,800,100:200,,1,2,0x00000200,56,2,2,4,100,1,10,{ bonus bUnbreakableWeapon; .@r = getrefine(); bonus bMatk,.@r/2*10; bonus2 bSkillAtk,"WL_JACKFROST",.@r/3*12; if (.@r>=9) { bonus2 bMagicAddEle,Ele_Water,7; } if (.@r>=11) { bonus2 bSkillCooldown,"WL_JACKFROST",-1000; bonus2 bMagicAddEle,Ele_Fire,7; } },{},{}
```
Also, arrange the order of ID

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +650004,Up_Humma_Clear,Patent Huuma Shuriken Clearness,5,20,,1300,230,,1,2,0x22000000,63,2,34,4,150,1,22,{ bonus bUnbreakableWeapon; .@r = getrefine(); bonus bBaseAtk,15*(.@r/2); bonus bLongAtkRate,.@
```suggestion
650004,Up_Humma_Clear,Patent Huuma Shuriken Clearness,5,20,,2300,290,,1,2,0x22000000,63,2,34,4,150,1,22,{ bonus bUnbreakableWeapon; .@r = getrefine(); bonus bBaseAtk,15*(.@r/2); bonus bLongAtkRate,.@r/3*2; if (.@r>=7){ bonus2 bSkillAtk,"KO_HUUMARANKA",30; bonus bVariableCastrate,-10; } if (.@r>=9){ bonus2 bSkillCooldown,"KO_HUUMARANKA",-1000; } if (.@r>=11){ bonus2 bAddEle,Ele_Fire,20; bonus2 bAddEle,Ele_Dark,20; bonus2 bAddEle,Ele_Holy,20; bonus2 bAddRace,RC_Undead,20; bonus2 bAddRace,RC_Demon,20; bonus2 bAddRace,RC_Angel,20; } },{},{}
```

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +700013,Up_Narcis_Bow,Patent Narcissus Bow,5,0,,1000,210,,5,2,0x00080800,58,2,34,4,150,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*15; if (.@r>=7){ bonus2 bSkillCooldown,"RA_ARROWSTORM",-2000; } if
```suggestion
700013,Up_Narcis_Bow,Patent Narcissus Bow,5,,,1000,210,,5,2,0x000A0800,56,2,34,4,150,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*15; bonus bLongAtkRate,.@r/3*4; if (.@r>=7){ bonus2 bSkillCooldown,"WM_SEVERE_RAINSTORM",-2000; } if (.@r>=9){ bonus2 bSkillAtk,"WM_SEVERE_RAINSTORM",15; } if (.@r>=11){ bonus2 bSkillAtk,"WM_SEVERE_RAINSTORM",10; bonus2 bWeaponDamageRate,W_BOW,15; } },{},{}
```

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +700018,Up_Royal_Bow_K,Patent Royal Bow,5,,,1200,205,,5,2,0x000A0808,63,2,34,3,150,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*15; bonus2 bSkillAtk,"RA_ARROWSTORM",13*(.@r/3); if (.@r>=7){ bonus bA
```suggestion
700018,Up_Royal_Bow_K,Patent Royal Bow,5,,,1200,205,,5,2,0x000A0800,56,2,34,4,150,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*15; bonus2 bSkillAtk,"RA_ARROWSTORM",12*(.@r/3); if (.@r>=7){ bonus bAspdRate,10; bonus2 bWeaponDamageRate,W_BOW,15; } if (.@r>=9){ bonus bLongAtkRate,12; bonus bCritAtkRate,10; } if (.@r>=11){ bonus2 bSkillAtk,"SN_SHARPSHOOTING",20; bonus bDelayRate,-10; } },{},{}
```

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +700003,Scalet_Dragon_L_Bow,Scarlet Dragon Leather Bow,5,,,800,170,,5,2,0x00000800,56,2,34,4,100,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*10; bonus bDelayRate,.@r/3*4; if (.@r>=9) { bonus2 bSkil
```suggestion
700003,Scalet_Dragon_L_Bow,Scarlet Dragon Leather Bow,5,,,800,170,,5,2,0x00000800,56,2,34,4,100,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*10; bonus bDelayRate,-(.@r/3*4); if (.@r>=9) { bonus2 bSkillAtk,"RA_AIMEDBOLT",35; } if (.@r>=11) { bonus2 bSkillCooldown,"RA_AIMEDBOLT",-1000; } },{},{}
```

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +700019,Up_Scalet_Dragon_L_Bow,Patent Scarlet Dragon Leather Bow,5,,,900,200,,5,2,0x00000800,56,2,34,4,150,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*15; bonus bDelayRate,.@r/3*4; if (.@r>=7){ bon
```suggestion
700019,Up_Scalet_Dragon_L_Bow,Patent Scarlet Dragon Leather Bow,5,,,900,200,,5,2,0x00000800,56,2,34,4,150,1,11,{ .@r = getrefine(); bonus bBaseAtk,.@r/2*15; bonus bDelayRate,-(.@r/3*4); if (.@r>=7){ bonus bLongAtkRate,10; bonus2 bAddSize,Size_All,10; } if (.@r>=9){ bonus2 bSkillAtk,"RA_AIMEDBOLT",35; } if (.@r>=11){ bonus2 bSkillCooldown,"RA_AIMEDBOLT",-1000; bonus bVariableCastrate,-10; } },{},{}
```

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +820001,Up_Demon_Slayer_Shot,Patent Demon Slayer Shot,5,,,1400,275,,9,2,0x40000000,63,2,34,4,150,1,20,{ .@r = getrefine(); bonus bSplashRange,1; bonus bLongAtkRate,3*(.@r/2); bonus bMaxSPrate,2*(.@r/3
```suggestion
820001,Up_Demon_Slayer_Shot,Patent Demon Slayer Shot,5,,,2300,295,,9,2,0x40000000,63,2,34,4,150,1,20,{ .@r = getrefine(); bonus bSplashRange,1; bonus bLongAtkRate,3*(.@r/2); bonus bMaxSPrate,2*(.@r/3); if (.@r>=7){ bonus2 bAddClass,Class_Boss,15; bonus2 bAddRace,RC_Undead,15; bonus2 bAddRace,RC_Demon,15; } if (.@r>=9){ autobonus3 "{ bonus bBaseAtk,50; bonus bLongAtkRate,10; }",1000,90000,"RL_P_ALTER"; } if (.@r>=11){ bonus2 bSkillAtk,"RL_BANISHING_BUSTER",35; bonus2 bSkillAtk,"RL_S_STORM",35; } },{},{}
```

2020-09-12 02:38 UTC, crazy-arashi commented on db/re/item_db.txt
> +830002,Up_The_Black,Patent The Black,5,,,3000,225,,9,2,0x40000000,63,2,34,4,150,1,19,{ .@r = getrefine(); bonus bBaseAtk,15*(.@r/2); bonus bLongAtkRate,4*(.@r/3); if (.@r>=7){ bonus2 bSkillAtk,"RL_R_
```suggestion
830002,Up_The_Black,Patent The Black,5,,,3000,225,,9,2,0x40000000,63,2,34,4,150,1,19,{ .@r = getrefine(); bonus bBaseAtk,15*(.@r/2); bonus bLongAtkRate,4*(.@r/3); if (.@r>=7){ bonus2 bSkillAtk,"RL_R_TRIP",20; bonus2 bSkillUseSPrate,"RL_R_TRIP",10; } if (.@r>=9){ bonus2 bSkillAtk,"RL_R_TRIP",15; autobonus3 "{ bonus bBaseAtk,50; bonus bLongAtkRate,10; }",1000,90000,"RL_P_ALTER"; } if (.@r>=11){ bonus2 bAddSize,Size_All,15; } },{},{}
```

2020-09-12 03:08 UTC, kaninhot004 commented
Thank you @crazy-arashi !

All changes is done.

2020-09-12 06:49 UTC, crazy-arashi approved these changes

2020-09-15 13:11 UTC, Atemo commented
Do you mind to update the item sql too in your PRs? (uses the tool https://github.com/rathena/rathena/blob/master/tools/convert_sql.pl)

2020-09-15 13:19 UTC, kaninhot004 commented
> Do you mind to update the item sql too in your PRs? (uses the tool https://github.com/rathena/rathena/blob/master/tools/convert_sql.pl)

Yep, I will try that.

2020-09-26 12:57 UTC, Atemo requested changes
GW !

2020-09-27 05:34 UTC, kaninhot004 commented
All changes has been fixed. Thank you @Atemo

2020-09-27 17:31 UTC, Atemo approved these changes

2020-09-27 17:58 UTC, crazy-arashi requested changes

2020-09-27 17:58 UTC, crazy-arashi commented on db/re/item_combo_db.txt
> +//22238:820001,{ bonus bDex,10; bonus bLongAtkRate,5; } /*Not had item in item_db yet*/
Please remove the comments. 22238 is in the database already.

2020-09-28 06:26 UTC, crazy-arashi approved these changes

2020-09-28 12:02 UTC, aleos89 approved these changes

2020-09-28 12:42 UTC, merged

2020-09-28 12:43 UTC, Atemo commented
Thanks!