Session check standarization
rathena/rathena pull request #5388
Opened 2020-09-08 19:56 UTC by Daegaladh

* **Addressed Issue(s)**: N/A

* **Server Mode**: Both

* **Description of Pull Request**:

2020-09-14 14:26 UTC, secretdataz commented
Please flag both relevant functions as inline while you're at it.

2020-09-14 15:19 UTC, Lemongrass3110 requested changes
I agree with @secretdataz that it would be a good improvement to inline these functions while we are it.

Looks good in general only missed a few references that I found by searching for "fd" variable references. Might be that we inherited some other creative variable names though. But we can always fix these later on.

Beside my in-code-comments I saw that you missed two files completely: intif.cpp and script.cpp
Please check them for references too.

2020-09-14 15:19 UTC, Lemongrass3110 commented on src/char/char_logif.cpp
> +	if (session_isValid(login_fd))
Replace with chlogif_isconnected()

2020-09-14 15:19 UTC, Lemongrass3110 commented on src/char/char_logif.cpp
> +	if (session_isValid(login_fd))
```suggestion
	if (chlogif_isconnected())
```

2020-09-14 15:19 UTC, Lemongrass3110 commented on src/char/char_mapif.cpp
> +	if (session_isValid(fd)) {
You missed two cases above. In chmapif_sendall and chmapif_sendallwos. Please also change them.

2020-09-14 15:19 UTC, Lemongrass3110 commented on src/map/clif.cpp
> +	if (session_isValid(fd))
Missing clif_authfail_fd

2020-09-28 12:17 UTC, aleos89 commented
I think what @secretdataz and @Lemongrass3110 commented on are good as well.

2021-01-13 21:19 UTC, aleos89 approved these changes

2021-01-14 10:02 UTC, Lemongrass3110 approved these changes

2021-01-14 14:57 UTC, merged