Fixes achievements and multi level up events
rathena/rathena pull request #5425
Opened 2020-09-28 17:24 UTC by aleos89

* **Addressed Issue(s)**: Fixes #5413

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Fixes an issue where achievements that check for specific base/job level events don't get triggered if battle_config.multi_level_up is enabled.
Thanks to @saya9200!

2020-09-28 23:05 UTC, saya9200 commented
IDK if it's just on my live server like this. I have some modifications but not really achievement related.

1) I complete quest "12345" // but I dont have an achievement reward set for it yet.

2) Add a new achievement to the server that requires this quest to be complete.

3) server goes up -> you login with the char that completed the quest -> but dont get the achievement for it.

2020-09-29 20:48 UTC, Lemongrass3110 requested changes

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/atcommand.cpp
> +		for (uint16 i = 1; i <= (sd->status.base_level - level); i++) {
```suggestion
		for (uint16 i = sd->status.base_level - level; i <= sd->status.base_level; i++) {
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/atcommand.cpp
> +			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, level + i);
```suggestion
			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, i);
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/atcommand.cpp
> +			achievement_update_objective(sd, AG_GOAL_STATUS, 2, level + i, sd->status.class_);
```suggestion
			achievement_update_objective(sd, AG_GOAL_STATUS, 2, i, sd->status.class_);
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/atcommand.cpp
> +		for (uint16 i = 1; i <= (sd->status.job_level - level); i++)
```suggestion
		for (uint16 i = sd->status.job_level - level; i <= sd->status.job_level; i++)
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/atcommand.cpp
> +			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, level + i);
```suggestion
			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, i);
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/pc.cpp
> +	for (uint16 i = 1; i <= (sd->status.base_level - base_level); i++) {
```suggestion
	for (; base_level <= sd->status.base_level; base_level++) {
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/pc.cpp
> +		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, base_level + i);
```suggestion
		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, base_level);
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/pc.cpp
> +		achievement_update_objective(sd, AG_GOAL_STATUS, 2, base_level + i, sd->status.class_);
```suggestion
		achievement_update_objective(sd, AG_GOAL_STATUS, 2, base_level, sd->status.class_);
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/pc.cpp
> +	for (uint16 i = 1; i <= (sd->status.job_level); i++)
```suggestion
	for (; job_level <= sd->status.job_level; job_level++)
```

2020-09-29 20:48 UTC, Lemongrass3110 commented on src/map/pc.cpp
> +		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, job_level + 1);
```suggestion
		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, job_level);
```

2020-09-29 20:50 UTC, Lemongrass3110 commented
> 
> 
> IDK if it's just on my live server like this. I have some modifications but not really achievement related.
> 
>     1. I complete quest "12345" // but I dont have an achievement reward set for it yet.
> 
>     2. Add a new achievement to the server that requires this quest to be complete.
> 
>     3. server goes up -> you login with the char that completed the quest -> but dont get the achievement for it.

Create a seperate issue for this and give a sample YML entry so we can test.
It is hard to tell what is wrong if you do not say how you even check the quest state.

2020-09-30 17:32 UTC, Lemongrass3110 approved these changes

2020-10-02 14:05 UTC, merged

2024-02-17 20:04 UTC, BotGigo commented
This issue still present today, im using a very fresh version of rathena.

![imagen](https://github.com/rathena/rathena/assets/59173632/03a620d0-26ce-4714-b250-54c0f0c81210)