Fix several honor token items and add Prontera Recall skill
rathena/rathena pull request #5431
Opened 2020-10-03 18:18 UTC by Latiosu

* **Addressed Issue(s)**: None

* **Server Mode**: Both

* **Description of Pull Request**: 

Following changes are made:
1. Add item effect for City Map (source: https://www.divine-pride.net/database/item/28354)
2. Add item effect for Shining Holy Water (source: https://www.divine-pride.net/database/item/28355)
3. Add item effect for Prontera Badge (source: https://www.divine-pride.net/database/item/22847)
4. Implement "Return to Prontera" skill used by Prontera Badge item (source: https://www.divine-pride.net/database/skill/3042)

2020-10-06 17:05 UTC, aleos89 requested changes
If you could also adjust 22847 in this PR:
```
22847,BadgeOfProntera,Prontera Badge,2,10,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ warp "prontera",159,192; },{},{}
```
The coordinates are correct, and the item name is wrong.

2020-10-06 17:05 UTC, aleos89 commented on db/re/item_db.txt
> +28355,Shining_Holy_Water_,Shining Holy Water,4,0,,100,,0,,1,0xFFFFFFFF,63,2,136,,1,0,0,{ bonus2 bHPRegenRate,100,10000; bonus2 bSPRegenRate,5,10000; bonus2 bAddDefMonster,3445,20; bonus2 bAddDefMonst
```suggestion
28355,ShiningHolyWater_,Shining Holy Water [1],4,0,,100,,0,,1,0xFFFFFFFF,63,2,136,,1,0,0,{ bonus2 bHPRegenRate,100,10000; bonus2 bSPRegenRate,5,10000; bonus2 bAddDefMonster,3445,20; bonus2 bAddDefMonster,3446,20; bonus2 bAddDefMonster,3447,20; bonus2 bAddDefMonster,3448,20; bonus2 bAddDefMonster,3449,20; bonus2 bAddDefMonster,3450,20; bonus2 bAddDefMonster,3451,20; bonus2 bAddDefMonster,3452,20; },{},{}
```

2020-10-06 17:05 UTC, aleos89 commented on db/re/item_db.txt
> +28356,Prontera_Badge,Prontera Badge,4,0,,100,,0,,0,0xFFFFFFFF,63,2,136,,1,0,0,{ skill "ALL_PRONTERA_RECALL",2; },{},{}
```suggestion
28356,BadgeOfProntera_,Prontera Badge,4,0,,100,,0,,0,0xFFFFFFFF,63,2,136,,1,0,0,{ skill "ALL_PRONTERA_RECALL",2; },{},{}
```

2020-10-06 17:05 UTC, aleos89 commented on db/re/item_delay.txt
> +28356,900000    //Prontera_Badge
```suggestion
28356,900000    //BadgeOfProntera_
```

2020-10-17 22:34 UTC, Latiosu commented
> If you could also adjust 22847 in this PR:
> 
> ```
> 22847,BadgeOfProntera,Prontera Badge,2,10,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ warp "prontera",159,192; },{},{}
> ```
> 
> The coordinates are correct, and the item name is wrong.

Apologies for the delay with this, I had missed it earlier.

2020-10-18 01:06 UTC, aleos89 approved these changes

2020-10-25 23:54 UTC, Lemongrass3110 approved these changes

2020-10-26 14:18 UTC, Atemo approved these changes

2020-10-26 19:44 UTC, merged