Corrects a couple items
rathena/rathena pull request #5437
Opened 2020-10-08 14:33 UTC by aleos89

* **Addressed Issue(s)**: Fixes #5420

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Fixes Robot's Arm, Gigantic Blade, and Tornado Axe buy/sell price, range, and job equip.
Thanks to @mazvi!

2020-10-09 14:13 UTC, Atemo requested changes

2020-10-09 14:13 UTC, Atemo commented on db/re/item_db.txt
> +16033,Robot's_Arm,Robot's Arm,5,30000,,3000,195,,5,2,0x0004C5B2,56,2,2,4,130,1,8,{ bonus bUnbreakableWeapon; bonus bCritical,20; },{},{}
The range were fine according to aegis data
```suggestion
16033,Robot's_Arm,Robot's Arm,5,30000,,3000,195,,1,2,0x0004C5B2,56,2,2,4,130,1,8,{ bonus bUnbreakableWeapon; bonus bCritical,20; },{},{}
```

2020-10-09 14:13 UTC, Atemo commented on db/re/item_db.txt
> +21011,Giant_Blade,Gigantic Blade,5,30000,,5000,300,,5,1,0x00004082,56,2,34,4,130,1,3,{ bonus bUnbreakableWeapon; bonus bAspdRate,-5; bonus bCritAtkRate,getrefine(); if(readparam(bStr)<=110){ bonus bA
The range were fine according to aegis data
```suggestion
21011,Giant_Blade,Gigantic Blade,5,30000,,5000,300,,1,1,0x00004082,56,2,34,4,130,1,3,{ bonus bUnbreakableWeapon; bonus bAspdRate,-5; bonus bCritAtkRate,getrefine(); if(readparam(bStr)<=110){ bonus bAtk,-250; } },{},{}
```

2020-10-09 14:13 UTC, Atemo commented on db/re/item_db.txt
> +28101,Tornado_Axe,Tornado Axe,5,30000,,4000,320,,5,1,0x000444A2,56,2,34,4,100,1,7,{ bonus bAtkEle,Ele_Wind; bonus2 bSkillCooldown,"NC_AXETORNADO",-1000; },{},{}
```suggestion
28101,Tornado_Axe,Tornado Axe,5,30000,,4000,320,,1,1,0x000444A2,56,2,34,4,100,1,7,{ bonus bAtkEle,Ele_Wind; bonus2 bSkillCooldown,"NC_AXETORNADO",-1000; },{},{}
```

2020-10-09 14:13 UTC, Atemo commented on sql-files/item_db_re.sql
> +REPLACE INTO `item_db_re` VALUES (16033,'Robot\'s_Arm','Robot\'s Arm',5,30000,NULL,3000,'195',NULL,5,2,0x0004C5B2,56,2,2,4,'130',1,8,'bonus bUnbreakableWeapon; bonus bCritical,20;',NULL,NULL);
```suggestion
REPLACE INTO `item_db_re` VALUES (16033,'Robot\'s_Arm','Robot\'s Arm',5,30000,NULL,3000,'195',NULL,1,2,0x0004C5B2,56,2,2,4,'130',1,8,'bonus bUnbreakableWeapon; bonus bCritical,20;',NULL,NULL);
```

2020-10-09 14:13 UTC, Atemo commented on sql-files/item_db_re.sql
> +REPLACE INTO `item_db_re` VALUES (21011,'Giant_Blade','Gigantic Blade',5,30000,NULL,5000,'300',NULL,5,1,0x00004082,56,2,34,4,'130',1,3,'bonus bUnbreakableWeapon; bonus bAspdRate,-5; bonus bCritAtkRat
```suggestion
REPLACE INTO `item_db_re` VALUES (21011,'Giant_Blade','Gigantic Blade',5,30000,NULL,5000,'300',NULL,1,1,0x00004082,56,2,34,4,'130',1,3,'bonus bUnbreakableWeapon; bonus bAspdRate,-5; bonus bCritAtkRate,getrefine(); if(readparam(bStr)<=110){ bonus bAtk,-250; }',NULL,NULL);
```

2020-10-09 14:13 UTC, Atemo commented on sql-files/item_db_re.sql
> +REPLACE INTO `item_db_re` VALUES (28101,'Tornado_Axe','Tornado Axe',5,30000,NULL,4000,'320',NULL,5,1,0x000444A2,56,2,34,4,'100',1,7,'bonus bAtkEle,Ele_Wind; bonus2 bSkillCooldown,"NC_AXETORNADO",-100
```suggestion
REPLACE INTO `item_db_re` VALUES (28101,'Tornado_Axe','Tornado Axe',5,30000,NULL,4000,'320',NULL,1,1,0x000444A2,56,2,34,4,'100',1,7,'bonus bAtkEle,Ele_Wind; bonus2 bSkillCooldown,"NC_AXETORNADO",-1000;',NULL,NULL);
```

2020-10-19 15:29 UTC, Lemongrass3110 approved these changes

2020-10-19 17:41 UTC, Atemo approved these changes

2020-10-19 18:54 UTC, merged