Converts the random option databases to YAML
rathena/rathena pull request #5494
Opened 2020-10-28 00:53 UTC by aleos89

* **Addressed Issue(s)**: Fixes #3084

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Creating random option groups now further reflects official behavior.
  * Group bonuses can now be created without having to create multiple permutations of the same group.
  * Specific slot options can now be defined which guarantee a bonus.
  * Non-guaranteed options can now be defined along with a maximum amount.
  * Random option value can now be defined as a range instead of a static value.
  * Adds conversion of official random option groups.
  * Includes CSV2YAML conversion tool.

2020-11-05 21:41 UTC, Lemongrass3110 requested changes

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +		if (random_option_db.option_search_name(name)) {
Should only trigger, if the found id != the current id, otherwise it could be someone redefined the name in the import file.

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +bool RandomOptionDatabase::option_get_id(std::string name, uint16 *id) {
Make id a reference, this way it cannot be nullptr and assignment does not require dereferencing.

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +		if (random_option_group.option_search_name(name)) {
Only trigger this, if the found id is not the same as the current one, otherwise it might be someone has redefined the group name in import.

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +			this->invalidWarning(slotNode, "Reached maximum of %d Random Option group options.\n", MAX_ITEM_RDM_OPT);
```suggestion
			this->invalidWarning(slotNode, "Reached maximum of %d Random Option group options. Skipping the remaining slots...\n", MAX_ITEM_RDM_OPT);
```

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +		int16 slot;
If it is [1-x[ make it uint16 maybe?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +			this->invalidWarning(slotNode["Slot"], "Invalid Random Opton Slot number %d given, must be between 1~%d, skipping.\n", slot, MAX_ITEM_RDM_OPT);
int16 should be %h or uint16 %hu

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +
Should be limited by MAX_ITEM_RDM_OPT?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +			this->invalidWarning(node["Random"], "No Random options can be added because there are no Random Option slots available.\n", MAX_ITEM_RDM_OPT);
Unused argument?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +			return 0;
Maybe break and only skip, like you did above?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +			std::shared_ptr<s_random_opt_group_entry> entry;
If I am not mistaken this code and the code above do the same thing and should be put into a sub function maybe?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +bool RandomOptionGroupDatabase::option_search_name(std::string name) {
Rename to option_exists?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.cpp
> +bool RandomOptionGroupDatabase::option_get_id(std::string name, uint16 *id) {
Change to reference?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/itemdb.hpp
>  struct s_random_opt_group {
Plural name for the vectors?

2020-11-05 21:41 UTC, Lemongrass3110 commented on src/map/mob.cpp
> +			for (size_t i = 0; i < group->max_random; i++) {
I think the inner and outer loop should be switched a little maybe or merged?

Pseudo code:
```
for (size_t i = 0; i < min( group->max_random, MAX_ITEM_RDM_OPT ); i++) {
	// If it already has a option  - skip it
	if (item->option[j].id > 0)
		continue;
	// Apply random logic
}
```

Random logic from here and above could be put into a sub function again.

2020-11-05 21:41 UTC, Lemongrass3110 commented on db/re/item_randomopt_group.yml
> +  - Id: 0
Should be removed if it does not any effect?

2020-11-08 15:05 UTC, Lemongrass3110 approved these changes

2020-11-08 17:21 UTC, merged

2021-01-29 20:40 UTC, ijped27 commented
Is there any possible way to revert this commit or can i clone this and revert this and how