Questinfo correction
rathena/rathena pull request #5523
Opened 2020-11-05 01:29 UTC by Atemo

* **Addressed Issue(s)**: -

* **Server Mode**: -

* **Description of Pull Request**: 

The bubble from `questinfo` script command wasn't always displayed when several `questinfo` were defined in a npc.

Additional note: the `questinfo` is no longer automatically duplicated from the original npc inside an instance, it now need to be defined under `OnInstanceInit`.

2020-11-26 19:45 UTC, lighta commented
"Additional note: the questinfo is no longer automatically duplicated from the original npc inside an instance, it now need to be defined under OnInstanceInit."
Did we check if this won't break some existing script ? How can user detect if they script need fixing ? Can we have a small parser in tools for this ?

2020-11-27 13:56 UTC, Atemo commented
>How can user detect if they script need fixing ? Can we have a small parser in tools for this ?

A parser for this seems overkill but we can add additional notes in the docs or look deeper in the code to keep the old behaviour maybe

2021-01-14 14:51 UTC, aleos89 requested changes
Overall looks good! Just a few notes to use some C++ features.

2021-01-14 14:51 UTC, aleos89 commented on src/map/map.cpp
> +		map_free_questinfo(mapdata);
```suggestion
		map_free_questinfo(map_getmapdata(i));
```

2021-01-14 14:51 UTC, aleos89 commented on src/map/pc.cpp
> +					sd->qi_display[i].color = static_cast<e_questinfo_markcolor>(qi.color);
Do these need to be casted if they are of the same type?

2021-01-14 14:51 UTC, aleos89 commented on src/map/pc.cpp
> +				sd->qi_display[i].color = static_cast<e_questinfo_markcolor>(QMARK_NONE);
Same question, these shouldn't need to be casted if they are of the same type.

2021-01-14 14:51 UTC, aleos89 commented on src/map/pc.cpp
> +	CREATE(sd->qi_display, struct s_qi_display, (sd->qi_count = mapdata->qi_npc.size()));
Might be best to drop CREATE in favor of a vector.

2021-01-14 14:51 UTC, aleos89 commented on src/map/pc.hpp
> +	struct s_qi_display *qi_display;
```suggestion
	std::vector<std::shared_ptr<s_qi_display>> qi_display;
```

This step will require a bit of logic cleanup `pc_show_questinfo_reinit`.

2021-01-14 14:51 UTC, aleos89 commented on src/map/pc.hpp
>  	int qi_count;
```suggestion
```

2021-01-14 14:51 UTC, aleos89 commented on src/map/unit.cpp
>  			sd->qi_count = 0;
This whole block can be removed once utilizing shared_ptr/vector.

2021-01-15 17:05 UTC, Lemongrass3110 approved these changes

2021-01-15 17:31 UTC, aleos89 approved these changes

2021-01-15 21:49 UTC, merged