Suggestion: ALL_THIRD in item_db.yml
rathena/rathena pull request #5535
Opened 2020-11-10 13:23 UTC by Atemo

* **Addressed Issue(s)**: -

* **Server Mode**: -

* **Description of Pull Request**: 

Simple suggestion to combine the 3 types of third classes in a mask.

2020-11-10 13:51 UTC, Daegaladh approved these changes

2020-11-17 11:29 UTC, Lemongrass3110 requested changes
Can you please add the code for All_Upper & All_Baby to yaml2sql? Would have been a pain to do this on Github sorry...

Also it  might be good to integrate these changes into csv2yaml?

Are you going to update the database in a seperate pull/commit, after this has been merged?

2020-11-17 11:29 UTC, Lemongrass3110 commented on src/map/itemdb.hpp
> +	ITEMJ_ALL_THIRD   = 0x38,
```suggestion

```

2020-11-17 11:29 UTC, Lemongrass3110 commented on src/map/itemdb.hpp
```suggestion

	ITEMJ_ALL_UPPER = ITEMJ_UPPER | ITEMJ_THIRD_UPPER,
	ITEMJ_ALL_BABY = ITEMJ_BABY | ITEMJ_THIRD_BABY,
	ITEMJ_ALL_THIRD = ITEMJ_THIRD | ITEMJ_THIRD_UPPER | ITEMJ_THIRD_BABY,

```

2020-11-17 11:29 UTC, Lemongrass3110 commented on doc/item_db.txt
> +All_Third   - Applies to all Third classes.
```suggestion
All_Upper   - All Transcedent classes
All_Baby    - All baby classes
All_Third   - Applies to all Third classes.
```

2020-11-17 11:29 UTC, Lemongrass3110 commented on src/map/script_constants.hpp
> +	export_constant(ITEMJ_ALL_THIRD);
```suggestion
	export_constant(ITEMJ_ALL_UPPER);
	export_constant(ITEMJ_ALL_BABY);
	export_constant(ITEMJ_ALL_THIRD);
```

2020-11-17 11:29 UTC, Lemongrass3110 commented on src/map/script_constants.hpp
> +	export_constant2("EQP_Both_Hand", (EQP_HAND_R|EQP_HAND_L));
Do not ask me why, but there are some additional EQP defines inside pc.hpp

This should use: EQP_ARMS

2020-11-17 14:40 UTC, Atemo commented
>Also it might be good to integrate these changes into csv2yaml?
Are you going to update the database in a seperate pull/commit, after this has been merged?

Yes.
I will update the DB in this PR.

2020-11-18 20:42 UTC, Lemongrass3110 approved these changes

2020-11-19 15:03 UTC, merged

2020-11-20 16:40 UTC, jl1990 commented
This is causing issues:

`[Error]: Occurred in file 'db/re/item_db_usable.yml' on line 11886 and column 17.
[Error]: Invalid class upper All_Third, defaulting to All.
[Error]: Occurred in file 'db/re/item_db_usable.yml' on line 43530 and column 17.
[Error]: Invalid class upper All_Third, defaulting to All.
[Error]: Occurred in file 'db/re/item_db_usable.yml' on line 46327 and column 17.
[Status]: Done reading '3432' entries in 'db/re/item_db_usable.yml'
[Error]: Invalid equip location Both_Hand, defaulting to IT_ETC.
[Error]: Occurred in file 'db/re/item_db_equip.yml' on line 506 and column 17.
[Error]: Item type is not a weapon, defaulting to 0.
[Error]: Occurred in file 'db/re/item_db_equip.yml' on line 507 and column 17.
[Error]: Invalid equip location Both_Hand, defaulting to IT_ETC.
[Error]: Occurred in file 'db/re/item_db_equip.yml' on line 525 and column 17.
[Error]: Item type is not a weapon, defaulting to 0.
[Error]: Occurred in file 'db/re/item_db_equip.yml' on line 526 and column 17.
`