Fix Friendlist disappear
rathena/rathena pull request #5583
Opened 2020-11-29 10:12 UTC by attackjom

- fix friend list disappear in client 2020-09-02ragexeRE+

* **Addressed Issue(s)**: https://github.com/rathena/rathena/issues/5582

* **Server Mode**: Renewal

* **Description of Pull Request**: 
Fix a problem that friend list disappear in 2020-09-02ragexeRE.

2020-11-29 16:31 UTC, Lemongrass3110 requested changes
Your check has to be changed. If PACKETVER_RE_NUM is not defined it will result in 0 < 20200902 and will therefore be true.

2020-11-29 20:06 UTC, Lemongrass3110 approved these changes
Just a "beauty" correction, to match the other ifdef.

2020-11-29 20:06 UTC, Lemongrass3110 commented on src/map/clif.cpp
>  	const int size = 8 + NAME_LENGTH;
```suggestion
#if PACKETVER < 20180221 || PACKETVER_RE_NUM >= 20200902
	const int size = 8 + NAME_LENGTH;
#else
	const int size = 8;
```

2020-11-29 20:09 UTC, merged

2020-12-04 20:33 UTC, Balferian commented
After this fix nothing changed.
Tested on **2020-09-02aRagexeRE** and **2020-09-02bRagexeRE**.
(UI) After relogin friend list is clear.
![image](https://user-images.githubusercontent.com/16213511/101211695-a19ff900-3688-11eb-9c30-361409e0ed70.png)

2020-12-04 21:48 UTC, attackjom commented
> After this fix nothing changed.
> Tested on **2020-09-02aRagexeRE** and **2020-09-02bRagexeRE**.
> (UI) After relogin friend list is clear.
> ![image](https://user-images.githubusercontent.com/16213511/101211695-a19ff900-3688-11eb-9c30-361409e0ed70.png)

you need to defind

#define PACKETVER_RE_NUM 20200902  in packet.hpp or define_post.hpp

2020-12-04 22:00 UTC, Balferian commented
> > After this fix nothing changed.
> > Tested on **2020-09-02aRagexeRE** and **2020-09-02bRagexeRE**.
> > (UI) After relogin friend list is clear.
> 
> you need to define
> 
> #define PACKETVER_RE_NUM 20200902 in packet.hpp or define_post.hpp
@attackjom Thanks! Problem solved.