Fixes Bowling Bash behavior
rathena/rathena pull request #5598
Opened 2020-12-03 19:12 UTC by aleos89

* **Addressed Issue(s)**: #5489

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Removes the gutterline feature from Bowling Bash in renewal mode.
  * Skill will now behave as a normal 5x5 AoE.
  * Fixes knockback getting removed during battle calculation.
Thanks to @humanwizzard!

2020-12-04 03:57 UTC, humanwizzard commented
hit count increase depending on the number of targets with 2h sword: not working = always 2 hits 

knockback should be:
lv 1 ~ 2 = 1
lv 3 ~ 4 = 2
lv 5 ~ 6 = 3
lv 7 ~ 8 = 4
lv 9 ~ 10 = 5

2020-12-04 20:52 UTC, humanwizzard commented
knockback works strange now:
1 ~ 3 targets = knockback works
4 ~ 7 targets = no knockback
8 ~ 11 targets = knockback works
12 ~ 15 targets = no knockback
and so on

2020-12-12 04:15 UTC, humanwizzard commented
knockback works fine now but hit count got broken:
4 ~ 5 targets = 2 hit
6 ~ 7 targets = 3 hit

2020-12-16 15:04 UTC, humanwizzard commented
knockback works 2 times (2 ~ 10 cells) on all except one target and hit count works only on that target

2021-01-04 18:43 UTC, Daegaladh requested changes

2021-01-04 18:43 UTC, Daegaladh commented on src/map/skill.cpp
> +			skill_area_temp[0] = 0;
This line makes the recursive invocation not working properly

2021-01-04 18:46 UTC, Daegaladh requested changes

2021-01-04 18:46 UTC, Daegaladh commented on src/map/skill.cpp
> +			skill_area_temp[0] = 0;
This line makes recursive invocation not work properly

2021-01-07 08:04 UTC, Daegaladh approved these changes

2021-01-07 13:44 UTC, merged