Corrected script for item ID 16026
rathena/rathena pull request #5605
Opened 2020-12-05 08:31 UTC by idk-whoami

* **Addressed Issue(s)**: #5595

* **Server Mode**: re

* **Description of Pull Request**:

2020-12-05 17:30 UTC, Atemo requested changes

2020-12-05 17:30 UTC, Atemo commented on db/re/item_db_equip.yml
> +      .@r = getrefine(); bonus bBaseAtk,(.@r/3)*30; if(.@r>=9){ bonus3 bAutoSpell,"BS_WEAPONPERFECT",1,10; } if(.@r>=6){ bonus2 bAddClass,Class_All,5; }
There is an additional +5% when +9 
```suggestion
      .@r = getrefine(); bonus bBaseAtk,(.@r/3)*30; if(.@r>=9){ bonus2 bAddClass,Class_All,5; bonus3 bAutoSpell,"BS_WEAPONPERFECT",1,10; } if(.@r>=6){ bonus2 bAddClass,Class_All,5; }
```

2020-12-05 17:55 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      .@r = getrefine(); bonus bBaseAtk,(.@r/3)*30; if(.@r>=9){ bonus3 bAutoSpell,"BS_WEAPONPERFECT",1,10; } if(.@r>=6){ bonus2 bAddClass,Class_All,5; }
thanks

2020-12-05 18:25 UTC, Atemo approved these changes

2020-12-06 15:44 UTC, Daegaladh approved these changes

2020-12-06 19:06 UTC, merged