Fixes AddEffWhenHit not triggering Magic or Misc
rathena/rathena pull request #5628
Opened 2020-12-15 20:42 UTC by aleos89

* **Addressed Issue(s)**: Fixes #5623

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Fixes an issue with AddEffWhenHit not triggering on Magic or Misc type attacks.
Thanks to @24msz6eo!

2020-12-17 15:48 UTC, Atemo requested changes

2020-12-17 15:48 UTC, Atemo commented on src/map/skill.cpp
> +	if(dstsd && attack_type & (BF_WEAPON | BF_MAGIC | BF_MISC)) {	//Counter effects.
```suggestion
	if(dstsd && attack_type & BF_WEAPONMASK) {	//Counter effects.
```

2020-12-17 15:48 UTC, Atemo commented on src/map/skill.cpp
> +			if (!(it.flag & attack_type))
Type/value differents (`attack_type` : `BF_...`) (`it.flag` : `ATF_...`)

2020-12-20 21:37 UTC, 24msz6eo commented
bonus3 bAddEffWhenHit,Eff_Freeze,10000,ATF_WEAPON;

The above script will be effective for magic attacks

2020-12-25 02:22 UTC, 24msz6eo commented
This pr needs more judgment, for example, Garm Card, will become physical and magical attacks will be effective

2022-07-18 17:46 UTC, merged