Corrected script for some item
rathena/rathena pull request #5645
Opened 2020-12-21 09:18 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: 

Data correction for items 21001, 21002, 21004, 21006, 21016

https://divine-pride.net/database/item/21001
``````
update script
``````

https://divine-pride.net/database/item/21002
``````
update script
``````

https://divine-pride.net/database/item/21004
``````
remove job Swordman
update script
``````

https://divine-pride.net/database/item/21006
``````
update script
``````

https://divine-pride.net/database/item/21016
``````
update script
``````

2020-12-21 21:04 UTC, Lemongrass3110 requested changes

2020-12-21 21:04 UTC, Lemongrass3110 commented on db/re/item_db_equip.yml
> +         bonus bBaseAtk,((.@i-2)*5);
No change here?

2020-12-21 21:04 UTC, Lemongrass3110 commented on db/re/item_db_equip.yml
> +      bonus bMatk,pow(min(getrefine(),15),2);
```suggestion
      bonus bMatk,pow(min(getrefine(),15),2)/2;
```

2020-12-21 22:05 UTC, Atemo requested changes

2020-12-21 22:05 UTC, Atemo commented on db/re/item_db_equip.yml
> +         bonus bShortWeaponDamageReturn,20;
```suggestion
         bonus bShortWeaponDamageReturn,20;
         bonus bMagicDamageReturn,20;
```
according to aegis db

2020-12-22 04:02 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bAddEff2,Eff_Curse,10;
yes

2020-12-22 04:03 UTC, idk-whoami commented on db/re/item_db_equip.yml
>      Locations:
thanks

2020-12-22 04:04 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +         bonus bBaseAtk,((.@i-2)*5);
yes

2020-12-22 04:04 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus bMatk,pow(min(getrefine(),15),2);
thanks

2020-12-22 04:06 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +         bonus bShortWeaponDamageReturn,20;
thanks

2020-12-22 21:55 UTC, merged

2020-12-22 21:56 UTC, Atemo commented
Thanks !