Add missing Overseas Care Package items
rathena/rathena pull request #5687
Opened 2021-01-12 14:52 UTC by Latiosu

* **Addressed Issue(s)**: 

* **Server Mode**: Renewal

* **Description of Pull Request**: 

Adds following items (and their item combos):
- [Bunker Shield](https://www.divine-pride.net/database/item/2184)
- [Solomon's Key](https://www.divine-pride.net/database/item/2191)
- [Miracle Blue Rose](https://www.divine-pride.net/database/item/5878)
- [Exorcist Glasses](https://www.divine-pride.net/database/item/5916)
- [Monster Fish Gills](https://www.divine-pride.net/database/item/5921)
- [Dragon Knight Eye Patch](https://www.divine-pride.net/database/item/5924)
- [Zealotus Doll](https://www.divine-pride.net/database/item/5975)
- [Antonio's Coat](https://www.divine-pride.net/database/item/15249)
- [Ixion Wing](https://www.divine-pride.net/database/item/18129)
- [Magical Booster](https://www.divine-pride.net/database/item/18720)
- [Old Pink Poo Hat](https://www.divine-pride.net/database/item/18959)
- [Catherina Von Blood](https://www.divine-pride.net/database/item/19163)
- [Guardian Processor](https://www.divine-pride.net/database/item/19170)
- [Black Veil](https://www.divine-pride.net/database/item/19460) - Illusion of Vampire bonus is commented out as placeholder
- [Diabolus Wing](https://www.divine-pride.net/database/item/19495) - Temple of the Demon God bonuses are commented out as placeholder
- [Gardener Shoes](https://www.divine-pride.net/database/item/22050)
- [Gravekeeper Shoes](https://www.divine-pride.net/database/item/22052)
- [Dragon Trainer Shoes](https://www.divine-pride.net/database/item/22058)
- [Hunter Shoes](https://www.divine-pride.net/database/item/22060)
- [Mechanic's Shoes](https://www.divine-pride.net/database/item/22062)
- [Fisherman's Shoes](https://www.divine-pride.net/database/item/22091)
- [Exorcist's Shoes](https://www.divine-pride.net/database/item/22093)
- [Gardener Shoes](https://www.divine-pride.net/database/item/22094)
- [Fallen Angel Shoes](https://www.divine-pride.net/database/item/22096)
- [Dragon Trainer Shoes](https://www.divine-pride.net/database/item/22097)
- [Mechanic Shoes](https://www.divine-pride.net/database/item/22099)
- [Spirit King's Ring](https://www.divine-pride.net/database/item/28394)
- [Yin Yang Talisman](https://www.divine-pride.net/database/item/28560)
- [Rose Bundle A](https://www.divine-pride.net/database/item/23251)
- [Orleans's Bundle A](https://www.divine-pride.net/database/item/23252)
- [Black Shiba Inu Bundle A](https://www.divine-pride.net/database/item/23253)
- [Kardui Bundle A](https://www.divine-pride.net/database/item/23255)
- [Etran Bundle A](https://www.divine-pride.net/database/item/23266)
- [Pororoca Shoes Bundle A](https://www.divine-pride.net/database/item/23294)

2021-01-19 19:09 UTC, Atemo requested changes

2021-01-20 09:46 UTC, Latiosu commented on db/re/item_combo_db.txt
> +19170:1549,{ .@r = getequiprefinerycnt(EQI_HAND_R); .@aspd = 0; .@bonus1 = 0; .@bonus2 = 0; if (.@r >= 7) { .@aspd += 10; .@bonus1 += 30; .@bonus2 += 50; } if (.@r >= 9) { .@aspd += 10; .@bonus1 += 3
Oops I also forgot to apply the ASPD rate bonus here
```suggestion
19170:1549,{ .@r = getequiprefinerycnt(EQI_HAND_R); if (.@r >= 7) { .@aspd += 10; .@bonus1 += 30; .@bonus2 += 50; if (.@r >= 9) { .@aspd += 10; .@bonus1 += 30; .@bonus2 += 50; if (.@r >= 10) { bonus2 bSkillCooldown,"NC_PILEBUNKER",-1000; } } bonus2 bSkillAtk,NC_BOOSTKNUCKLE,.@bonus1; bonus2 bSkillAtk,NC_VULCANARM,.@bonus2; bonus bAspdRate,.@aspd; } }
```

2021-01-20 14:48 UTC, Atemo requested changes
Do you mind to update the SQL files too? (run yaml2sql tool)

2021-01-20 14:48 UTC, Atemo commented on db/re/item_combo_db.txt
> +15249:4243,{ bonus bDef,250; bonus2 bSubEle,Ele_All,5; bonus2 bSubEle,Ele_Dark,-5; skill "AL_TELEPORT",1; bonus4 bAutoSpellWhenHit,"AL_TELEPORT",1,-500,0; if (.@r >= 7) { bonus2 bResEff,Eff_Freeze,10
```suggestion
15249:4243,{ .@r = getequiprefinerycnt(EQI_ARMOR); bonus bDef,250; bonus2 bSubEle,Ele_All,5; bonus2 bSubEle,Ele_Dark,-5; skill "AL_TELEPORT",1; bonus4 bAutoSpellWhenHit,"AL_TELEPORT",1,-500,0; if (.@r >= 7) { bonus2 bResEff,Eff_Freeze,10000; if (.@r >= 9) { bonus bNoKnockback; } } }
```

2021-01-22 05:42 UTC, idk-whoami commented
> Do you mind to update the SQL files too? (run yaml2sql tool)

how to use tool
i'm looking for guide

2021-01-22 09:05 UTC, Latiosu commented
> > Do you mind to update the SQL files too? (run yaml2sql tool)
> 
> how to use tool
> i'm looking for guide

I put together a gist to help explain. Happy to continue the conversation over there 👍 
https://gist.github.com/Latiosu/ab4d2604c55f051cd4f2397718b01460

2021-01-24 14:52 UTC, merged

2021-01-24 14:52 UTC, Atemo commented
Thanks !