Corrected script for some item
rathena/rathena pull request #5692
Opened 2021-01-15 04:15 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: 

Data correction for items 18108, 18124, 18151, 21038, 24166, 24167

https://divine-pride.net/database/item/18108
https://divine-pride.net/database/item/18124
``````
remove bonus bUnbreakableWeapon
``````

https://divine-pride.net/database/item/18151
``````
insert skill level  DC_DANCINGLESSON to bonus bLongAtkRate 
``````

https://divine-pride.net/database/item/21038
https://divine-pride.net/database/item/24166
https://divine-pride.net/database/item/24167
``````
update script
``````

2021-01-16 15:39 UTC, Atemo requested changes

2021-01-16 15:39 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus bBaseAtk,.@r/2;
```suggestion
      bonus bBaseAtk,10*(.@r/2);
```

2021-01-16 15:39 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bIgnoreMdefClassRate,Class_Normal,5+(getrefine()/2);
From Aegis
```suggestion
      .@r = getrefine();
      bonus bMaxHP,.@r*10;
      bonus2 bIgnoreDefClassRate,Class_Normal,5+(.@r/2);
```

2021-01-16 15:39 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bIgnoreMdefClassRate,Class_Normal,5+(getrefine()/2);
From Aegis
```suggestion
      .@r = getrefine();
      bonus bMaxHP,.@r*10;
      bonus2 bIgnoreDefClassRate,Class_Normal,5+(.@r/2);
```

2021-01-17 06:46 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus bBaseAtk,.@r/2;
Thanks

2021-01-17 06:46 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bIgnoreMdefClassRate,Class_Normal,5+(getrefine()/2);
Thanks

2021-01-17 06:46 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bIgnoreMdefClassRate,Class_Normal,5+(getrefine()/2);
Thanks

2021-01-18 16:18 UTC, merged

2021-01-18 16:18 UTC, Atemo commented
Thanks!