Corrected script for some item
rathena/rathena pull request #6094
Opened 2021-07-17 17:31 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: 

Add items
https://www.divine-pride.net/database/item/1320
https://www.divine-pride.net/database/item/1325
https://www.divine-pride.net/database/item/1444
https://www.divine-pride.net/database/item/1842
https://www.divine-pride.net/database/item/1843
https://www.divine-pride.net/database/item/1945
https://www.divine-pride.net/database/item/1946
https://www.divine-pride.net/database/item/2035
https://www.divine-pride.net/database/item/2036
https://www.divine-pride.net/database/item/13130
https://www.divine-pride.net/database/item/13140
https://www.divine-pride.net/database/item/13141
https://www.divine-pride.net/database/item/13333
https://www.divine-pride.net/database/item/13334
https://www.divine-pride.net/database/item/13466
https://www.divine-pride.net/database/item/13467
https://www.divine-pride.net/database/item/15187
https://www.divine-pride.net/database/item/15188
https://www.divine-pride.net/database/item/16049
https://www.divine-pride.net/database/item/16058
https://www.divine-pride.net/database/item/16059
https://www.divine-pride.net/database/item/18133
https://www.divine-pride.net/database/item/18146
https://www.divine-pride.net/database/item/18147
https://www.divine-pride.net/database/item/20827
https://www.divine-pride.net/database/item/20828
https://www.divine-pride.net/database/item/21026
https://www.divine-pride.net/database/item/21027
https://www.divine-pride.net/database/item/22127
https://www.divine-pride.net/database/item/22128
https://www.divine-pride.net/database/item/26004
https://www.divine-pride.net/database/item/26005
https://www.divine-pride.net/database/item/26105
https://www.divine-pride.net/database/item/26106
https://www.divine-pride.net/database/item/26143
https://www.divine-pride.net/database/item/26144
https://www.divine-pride.net/database/item/26201
https://www.divine-pride.net/database/item/26202
https://www.divine-pride.net/database/item/27031
https://www.divine-pride.net/database/item/27032
https://www.divine-pride.net/database/item/28018
https://www.divine-pride.net/database/item/28019
https://www.divine-pride.net/database/item/28117
https://www.divine-pride.net/database/item/28118
https://www.divine-pride.net/database/item/28227
https://www.divine-pride.net/database/item/28228
https://www.divine-pride.net/database/item/28229
https://www.divine-pride.net/database/item/28230
https://www.divine-pride.net/database/item/28231
https://www.divine-pride.net/database/item/28232
https://www.divine-pride.net/database/item/28233
https://www.divine-pride.net/database/item/28234
https://www.divine-pride.net/database/item/28609
https://www.divine-pride.net/database/item/28610
https://www.divine-pride.net/database/item/28708
https://www.divine-pride.net/database/item/28722
https://www.divine-pride.net/database/item/28723
https://www.divine-pride.net/database/item/32001
https://www.divine-pride.net/database/item/32002

Data correction for item combo IDs 2053:19451
https://www.divine-pride.net/database/item/2053
https://www.divine-pride.net/database/item/19451

Data correction for item IDs 500007
https://www.divine-pride.net/database/item/500007

2021-07-17 20:56 UTC, mazvi commented
Please include this https://github.com/rathena/rathena/issues/6091

2021-07-19 14:04 UTC, mazvi commented
Need update again about item ID 22107 because on item_db_equip.yml inconsistent with other boots 

like another boots AGI DEX INT LUK VIT

https://www.divine-pride.net/database/item/22107/modified-str-boots

2021-07-31 13:55 UTC, Atemo requested changes

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(7*readparam(bInt)/10);
Precedence, the result is different
```suggestion
      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(readparam(bInt)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(7*readparam(bInt)/10);
```suggestion
      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(readparam(bInt)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_R_TRIP",(7*readparam(bAgi)/10);
```suggestion
      bonus2 bSkillAtk,"RL_R_TRIP",(readparam(bAgi)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_R_TRIP",(7*readparam(bAgi)/10);
```suggestion
      bonus2 bSkillAtk,"RL_R_TRIP",(readparam(bAgi)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_D_TAIL",(7*readparam(bLuk)/10);
```suggestion
      bonus2 bSkillAtk,"RL_D_TAIL",(readparam(bLuk)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_D_TAIL",(7*readparam(bLuk)/10);
```suggestion
      bonus2 bSkillAtk,"RL_D_TAIL",(readparam(bLuk)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_SLUGSHOT",(7*readparam(bStr)/10);
```suggestion
      bonus2 bSkillAtk,"RL_SLUGSHOT",(readparam(bStr)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_SLUGSHOT",(7*readparam(bStr)/10);
```suggestion
      bonus2 bSkillAtk,"RL_SLUGSHOT",(readparam(bStr)/10)*7;
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      Wizard: true
```suggestion
      Wizard: true
    Classes:
      All_Third: true
```

2021-07-31 13:55 UTC, Atemo commented on db/re/item_db_equip.yml
> +      Wizard: true
```suggestion
      Wizard: true
    Classes:
      All_Third: true
```

2021-07-31 16:24 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(7*readparam(bInt)/10);
Thanks

2021-07-31 16:24 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(7*readparam(bInt)/10);
Thanks

2021-07-31 16:25 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_R_TRIP",(7*readparam(bAgi)/10);
Thanks

2021-07-31 16:25 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_R_TRIP",(7*readparam(bAgi)/10);
Thanks

2021-07-31 16:25 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_D_TAIL",(7*readparam(bLuk)/10);
Thanks

2021-07-31 16:25 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_D_TAIL",(7*readparam(bLuk)/10);
Thanks

2021-07-31 16:26 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_SLUGSHOT",(7*readparam(bStr)/10);
Thanks

2021-07-31 16:26 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_SLUGSHOT",(7*readparam(bStr)/10);
Thanks

2021-07-31 16:26 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      Wizard: true
Thanks

2021-07-31 16:26 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      Wizard: true
Thanks

2021-08-02 12:17 UTC, merged

2021-08-02 12:17 UTC, Atemo commented
Thanks!