Implemented the item group IG_XMAS_PACKAGE_14, IG_EASTER_EGG and IG_PITAPAT_BOX
rathena/rathena pull request #6121
Opened 2021-07-22 23:02 UTC by Atemo

* **Addressed Issue(s)**: N/A

* **Server Mode**: renewal

* **Description of Pull Request**:

2021-07-23 03:52 UTC, idk-whoami requested changes

2021-07-23 03:52 UTC, idk-whoami commented on sql-files/item_db_re_equip.sql
> +REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_right_accessory`,`equip_level_min`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nocar
Something went wrong. Please revert.

2021-07-23 12:30 UTC, Atemo commented on sql-files/item_db_re_equip.sql
> +REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_right_accessory`,`equip_level_min`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nocar
What's wrong ?
I only ran yaml2sql tool

2021-07-28 17:37 UTC, Lemongrass3110 approved these changes

2021-07-31 12:31 UTC, merged