Corrected script for some item
rathena/rathena pull request #6172
Opened 2021-08-09 17:09 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**:

2021-08-09 19:42 UTC, Atemo requested changes

2021-08-09 19:42 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(7*readparam(bInt)/10);
```suggestion
      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",7*(readparam(bInt)/10);
```

2021-08-09 19:42 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_R_TRIP",(7*readparam(bAgi)/10);
```suggestion
      bonus2 bSkillAtk,"RL_R_TRIP",7*(readparam(bAgi)/10);
```

2021-08-09 19:42 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_SLUGSHOT",(7*readparam(bStr)/10);
```suggestion
      bonus2 bSkillAtk,"RL_SLUGSHOT",7*(readparam(bStr)/10);
```

2021-08-09 19:42 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_D_TAIL",(7*readparam(bLuk)/10);
```suggestion
      bonus2 bSkillAtk,"RL_D_TAIL",7*(readparam(bLuk)/10);
```

2021-08-10 03:42 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(7*readparam(bInt)/10);
Thanks!

2021-08-10 03:42 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_R_TRIP",(7*readparam(bAgi)/10);
Thanks!

2021-08-10 03:42 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_SLUGSHOT",(7*readparam(bStr)/10);
Thanks!

2021-08-10 03:42 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus2 bSkillAtk,"RL_D_TAIL",(7*readparam(bLuk)/10);
Thanks!

2021-08-10 16:29 UTC, merged

2021-08-10 16:29 UTC, Atemo commented
Thanks !