Fix SC_CHANGE not using max matk
rathena/rathena pull request #6382
Opened 2021-11-30 17:17 UTC by Tydus1

* Thanks to Hercules for the fix;

* **Addressed Issue(s)**:  None

* **Server Mode**: Pre-Renewal

* **Description of Pull Request**: Fix SC_CHANGE (HLIF mental change skill) to use max MATK on pre-renewal;

2021-12-05 22:52 UTC, Lemongrass3110 requested changes

2021-12-05 22:52 UTC, Lemongrass3110 commented on src/map/battle.cpp
> +			return status->matk_max; // [Aegis] simply uses raw max matk for base damage when Mental Charge active
```suggestion
#ifndef RENEWAL
		if (sc != NULL && sc->data[SC_CHANGE] != NULL)
			return status->matk_max; // [Aegis] simply uses raw max matk for base damage when Mental Charge active
#endif
```

2021-12-05 22:52 UTC, Lemongrass3110 commented on src/map/battle.cpp
> +			return status->matk_max; // [Aegis] simply uses raw max matk for base damage when Mental Charge active
Unlike in Hercules this function is called in Renewal in rAthena as well.
Therefore we have to add a preprocessor check.

2021-12-05 22:53 UTC, Lemongrass3110 commented
Originally fixed by @skyleo in HerculesWS/Hercules#3078

2021-12-06 13:49 UTC, Lemongrass3110 approved these changes

2021-12-06 17:49 UTC, Atemo approved these changes

2021-12-06 18:43 UTC, merged