Corrected script for some item
rathena/rathena pull request #6523
Opened 2022-01-16 14:07 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

2022-01-20 16:22 UTC, Atemo requested changes

2022-01-20 16:22 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus bMdef,10;
```suggestion
      bonus bUnbreakableShoes;
      bonus bMdef,10;
```

2022-01-20 16:22 UTC, Atemo commented on db/re/item_db_equip.yml
> +      bonus bMdef,10;
```suggestion
      bonus bUnbreakableShoes;
      bonus bMdef,10;
```

2022-01-20 16:22 UTC, Atemo commented on db/re/item_db_equip.yml
> +      .@val = getskilllv("GN_CARTBOOST");
If I'm not wrong `精錬 : 可 破損 : しない`
```suggestion
      .@val = getskilllv("GN_CARTBOOST");
      bonus bUnbreakableShoes;
```

2022-01-20 16:22 UTC, Atemo commented on db/re/item_db_equip.yml
> +      .@r = getrefine();
```suggestion
      .@r = getrefine();
      bonus bUnbreakableShoes;
```

2022-01-20 16:22 UTC, Atemo commented on db/re/item_combos.yml
> +      bonus2 bMagicAddSize,Size_All,1*(.@r/2);
```suggestion
      bonus2 bMagicAddSize,Size_All,(.@r/2);
```

2022-01-20 16:22 UTC, Atemo commented on db/re/item_db_equip.yml
> +      .@r = getrefine();
```suggestion
      .@r = getrefine();
      bonus bUnbreakableShoes;
```

2022-01-21 00:43 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      .@r = getrefine();
Thanks!

2022-01-21 00:43 UTC, idk-whoami commented on db/re/item_combos.yml
> +      bonus2 bMagicAddSize,Size_All,1*(.@r/2);
Thanks!

2022-01-21 00:43 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      .@r = getrefine();
Thanks!

2022-01-21 00:44 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      .@val = getskilllv("GN_CARTBOOST");
OK, Thanks!

2022-01-21 00:44 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus bMdef,10;
Thanks!

2022-01-21 00:44 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      bonus bMdef,10;
Thanks!

2022-01-21 00:45 UTC, idk-whoami commented on db/re/item_combos.yml
> +      skill "AB_JUDEX",.@r,1;
Thanks!

2022-01-21 00:45 UTC, idk-whoami commented on db/re/item_combos.yml
> +      skill "AB_JUDEX",.@r,1;
Thanks!

2022-01-21 00:45 UTC, idk-whoami commented on db/re/item_combos.yml
> +          - RingOfThought_TW
OK, Thanks!

2022-01-21 13:44 UTC, merged

2022-01-21 13:44 UTC, Atemo commented
Thanks!