Feature/ep19items
rathena/rathena pull request #6563
Opened 2022-01-27 00:50 UTC by Toshiro90

* **Addressed Issue(s)**: -

* **Server Mode**: Renewal

* **Description of Pull Request**: 

Adds over 500 new items for episode 19 (released on 2022-01-19 on kRO), as well as some missing ones contained in new item boxes.
Includes item combos and item groups, as well as trading and buyingstore flags.
Most items use generic AegisName entries (aegis_###) when no name could be found in client files.

2022-01-27 14:28 UTC, Atemo commented
There is a typo in item_db_etc `Location:` is ignored as it should be `Locations:`

2022-01-27 14:36 UTC, Toshiro90 commented
> There is a typo in item_db_etc `Location:` is ignored as it should be `Locations:`

Fixed.

2022-01-31 19:58 UTC, Atemo requested changes

2022-02-01 15:12 UTC, Lemongrass3110 reviewed
Only checked the source part.

2022-02-01 15:12 UTC, Lemongrass3110 commented on src/map/itemdb.hpp
> +	IG_Enchant_Stone_Box26,
```suggestion
	IG_LI_NYANGVINE_BOX1_26,
	IG_LI_NYANGVINE_BOX2_26,
	IG_LI_NYANGVINE_BOX3_26,
	IG_ENCHANT_STONE_BOX26,
```

2022-02-01 15:12 UTC, Lemongrass3110 commented on src/map/script_constants.hpp
> +	export_constant(IG_Enchant_Stone_Box26);
export_constant(IG_LI_NYANGVINE_BOX1_26);
	export_constant(IG_LI_NYANGVINE_BOX2_26);
	export_constant(IG_LI_NYANGVINE_BOX3_26);
	export_constant(IG_ENCHANT_STONE_BOX26);

2022-02-01 19:14 UTC, Atemo approved these changes
Good work!

2022-02-02 11:02 UTC, Everade approved these changes

2022-02-02 15:15 UTC, merged