Corrected script for some item #2
rathena/rathena pull request #6565
Opened 2022-01-27 04:19 UTC by idk-whoami

* **Addressed Issue(s)**: N/A

* **Server Mode**: re

* **Description of Pull Request**: Implementations + corrections of a bunch of items

2022-01-31 16:22 UTC, Atemo requested changes

2022-02-02 05:35 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +    Refineable: true
Thanks!

2022-02-02 05:35 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +    Refineable: true
Thanks!

2022-02-02 05:35 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +    Refineable: true
Thanks!

2022-02-02 05:36 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +    Refineable: true
Thanks!

2022-02-02 05:36 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +    Refineable: true
Thanks!

2022-02-02 18:58 UTC, merged

2022-02-02 18:58 UTC, Atemo commented
Good work!