Corrected script for some item #8
rathena/rathena pull request #7044
Opened 2022-06-19 17:19 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: Implementations + corrections of a bunch of items

2022-07-14 13:15 UTC, Atemo requested changes

2022-07-14 13:15 UTC, Atemo commented on db/re/item_db_equip.yml
> +         bonus2 bSkillCooldown,"RA_ARROWSTORM",300;
```suggestion
         bonus2 bSkillCooldown,"RA_ARROWSTORM",-300;
```

2022-07-15 04:45 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +         bonus2 bSkillCooldown,"RA_ARROWSTORM",300;
Thanks!

2022-07-15 04:46 UTC, idk-whoami commented on db/re/item_db_etc.yml
> +      bonus bDelayrate,getskilllv("NC_TRAININGAXE");
Thanks!

2022-07-15 04:46 UTC, idk-whoami commented on db/re/item_db_etc.yml
> +      bonus bDelayrate,getskilllv("GC_RESEARCHNEWPOISON")/2;
Thanks!

2022-07-15 04:46 UTC, idk-whoami commented on db/re/item_db_etc.yml
> +      bonus bVariableCastrate,getskilllv("NC_RESEARCHFE");
Thanks!

2022-07-15 12:57 UTC, Atemo approved these changes

2022-07-15 12:58 UTC, merged

2022-07-15 12:58 UTC, Atemo commented
Thanks!