change aegis name to official
rathena/rathena pull request #7083
Opened 2022-07-01 18:38 UTC by Takerio

* **Addressed Issue(s)**: 

* **Server Mode**: 
RE

* **Description of Pull Request**:

2022-07-14 13:15 UTC, Atemo requested changes

2022-07-14 13:15 UTC, Atemo commented on db/re/item_db_etc.yml
> +      bonus bDoubleRate,5;
```suggestion
```

2022-07-14 13:15 UTC, Atemo commented on db/re/item_db_etc.yml
> +      bonus bDoubleRate,15;
```suggestion
```

2022-09-04 22:19 UTC, Akkarinage commented
@Takerio can you update your Pull Request please.

In future, you need to create a new branch before doing any work and creating a Pull Request, as we can't remotely update your master branch.

2022-12-18 02:25 UTC, Lemongrass3110 commented
No update since 3 months.
Most likely already most of it was covered by now.

2022-12-18 02:25 UTC, closed without merging