Corrected script for some item #9
rathena/rathena pull request #7115
Opened 2022-07-17 15:14 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: Implementations + corrections of a bunch of items

2022-08-07 14:57 UTC, Atemo requested changes

2022-08-07 14:57 UTC, Atemo commented on db/re/item_db_equip.yml
> +      .@b = .@i;
```suggestion
      .@a = 5;
      .@b = BaseLevel/35;
```

2022-08-07 17:01 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      .@b = .@i;
Thanks!

2022-08-07 17:01 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      .@b = 2*.@i;
Thanks!

2022-08-07 17:01 UTC, idk-whoami commented on db/re/item_db_etc.yml
> +      .@val = readparam(bStr) +  readparam(bInt) +  readparam(bDex);
Thanks!

2022-08-07 17:01 UTC, idk-whoami commented on db/re/item_db_etc.yml
> +      bonus2 bIgnoreDefClassRate,Class_Boss,100;
Thanks!

2022-08-10 12:53 UTC, merged

2022-08-10 12:53 UTC, Atemo commented
Thanks!