Corrected NPC_DARKBREATH formula
rathena/rathena pull request #7285
Opened 2022-09-22 15:05 UTC by Singe-Horizontal

* **Addressed Issue(s)**: 
Fixes #7284

* **Server Mode**: 
Both

* **Description of Pull Request**: 
Corrects the NPC_DARKBREATH math formula

2022-09-22 15:12 UTC, Pokye commented on src/map/battle.cpp
> +			        ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * (6 - skill_lv)) : 50) / 100;
```suggestion
				ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * (6 - skill_lv)) : 50) / 100;
```
Remove <SPACE> and add <TAB>

2022-10-01 14:46 UTC, Lemongrass3110 approved these changes

2022-10-01 14:46 UTC, Lemongrass3110 commented on src/map/battle.cpp
> +				ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * (6 - skill_lv)) : 50) / 100;
```suggestion
				ad.damage = ( tstatus->hp * std::min( 10 * skill_lv, 50 ) ) / 100;
```
I would rather like to simplify the formula as a whole?

2023-04-19 12:21 UTC, Singe-Horizontal commented
Is anyone available to confirm this on aegis?

2023-04-19 16:04 UTC, Singe-Horizontal commented
I assumed you meant 2 * (6-skLevel) since it makes sense with the initial skLevel <= 5 test

2023-04-19 16:05 UTC, Daegaladh commented
Not sure if it's `2*(6-skLevel)` or `2*6-skLevel`, but if it's really the first case, there's no need to split it into pre-re/re
https://github.com/rathena/rathena/issues/4864#issuecomment-629578983

2023-04-19 16:27 UTC, Singe-Horizontal commented
In RE with that formula it would give : 10% 12,5% 16,67% 25% 50%

2023-04-19 17:22 UTC, Daegaladh commented
I know, 2*(6-skLevel) would make more sense, but need confirmation

2023-04-19 18:18 UTC, aleos89 approved these changes

2023-04-19 18:28 UTC, Daegaladh requested changes
We've confirmed it's `2*(6 - skill_lv)` , just remove the pre-re/re ifdef, as they're not necessary, it's the same for both

2023-04-20 08:12 UTC, Daegaladh approved these changes

2023-04-20 08:13 UTC, merged