Added Missing Shops Script
rathena/rathena pull request #7362
Opened 2022-10-14 21:46 UTC by Pokye

* **Addressed Issue(s)**: https://github.com/rathena/rathena/issues/6990

* **Server Mode**: Renewal

* **Description of Pull Request**: Still need to check the translation.

Thanks to @Balferian for discovering it, and to @Everade for helping me with a translation

2022-10-15 03:51 UTC, secretdataz requested changes

2022-10-15 03:51 UTC, secretdataz commented on npc/re/merchants/Emperium_Seller.txt
> +		mes "The Empelium to be distributed to the guild office today has arrived. If you want to purchase, please put as many as you want~";
Emperium

2022-10-15 03:51 UTC, secretdataz commented on npc/re/merchants/Emperium_Seller.txt
> +		mes "It seems that many people are looking for Empelium today. It's just a personal feeling.";
Emperium

2022-10-15 03:51 UTC, secretdataz commented on npc/re/merchants/Emperium_Seller.txt
> +	mes "Please note that our guild office does not sell because we have to run around to supply Empelium outside of the hours.";
Emperium

2022-10-15 10:12 UTC, Atemo commented on npc/re/merchants/Emperium_Seller.txt
> +	mes "Afternoon ^0000ff18:00~23:59^000000 is on sale.";
Maybe
```suggestion
	mes "As part of that,";
	mes "we are selling a limited quantity of 100 <ITEM>Emperium<INFO>714</INFO></ITEM> every day";
	mes "from ^0000ff18:00 to 23:59^000000 from ^0000ffMonday to Saturday^000000.";
```
is a bit better

2022-10-18 10:27 UTC, Atemo commented on npc/re/merchants/Emperium_Seller.txt
> +	if (gettime(DT_DAYOFWEEK) == 1) npcshopupdate "emp_seller#slo",714,0,100;
According to the translation, shouldn't the shop be updated every day?
```suggestion
OnHour00:
	npcshopupdate "emp_seller#slo",714,0,100;
```

2022-10-18 10:27 UTC, Atemo commented on npc/re/merchants/Slot_Move_Card_Sales.txt
> +	if (gettime(DT_DAYOFWEEK) == 1) npcshopupdate "change_slot#slo",12786,0,9999;
```suggestion
OnMon0000:
	npcshopupdate "change_slot#slo",12786,0,9999;
```

2022-10-18 10:27 UTC, Atemo commented on npc/re/merchants/Emperium_Seller.txt
> +    }
```suggestion
	}
```

2022-10-18 10:27 UTC, Atemo commented on npc/re/merchants/Emperium_Seller.txt
> +    	callshop "emp_seller#slo";
```suggestion
		callshop "emp_seller#slo";
```

2022-10-22 10:59 UTC, Atemo approved these changes

2022-10-22 13:02 UTC, aleos89 approved these changes

2022-10-23 11:54 UTC, merged