Update EDP require 1 list item cost from item_group_db
rathena/rathena pull request #7463
Opened 2022-11-29 11:27 UTC by idk-whoami

* **Addressed Issue(s)**: #7458

* **Server Mode**: re

* **Description of Pull Request**: Corrected script for Poison Bottle items IDs 678 & 22549 + update EDP require 1 list item cost from item_group_db

Thanks to @kaninhot004

2022-11-29 15:25 UTC, Lemongrass3110 requested changes

2022-11-29 15:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      switch( Class ) {
Please change this to use eaclass()

2022-11-29 15:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      switch( Class ) {
Please change this to use eaclass()

2022-11-29 16:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      case EAJ_SHADOW_CROSS:
```suggestion
      if ((eaclass()&EAJ_ASSASSIN_CROSS)==EAJ_ASSASSIN_CROSS) {
```

2022-11-29 16:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      Default:
```suggestion
      }
      else
```

2022-11-29 16:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      }
```suggestion
```

2022-11-29 16:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      case EAJ_SHADOW_CROSS:
```suggestion
      if ((eaclass()&EAJ_ASSASSIN_CROSS)==EAJ_ASSASSIN_CROSS) {
```

2022-11-29 16:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      Default:
```suggestion
      }
      else
```

2022-11-29 16:25 UTC, Lemongrass3110 commented on db/re/item_db_usable.yml
> +      }
```suggestion
```

2022-11-29 16:52 UTC, idk-whoami commented on src/map/skill.cpp
> +					clif_skill_fail(sd,skill_id,USESKILL_FAIL_LEVEL,0);
I'm sorry, I don't have an example. Get itemid and amount from itemdb_group.item_exists_pc to use with clif_skill_fail . T_T

2022-12-18 00:44 UTC, Lemongrass3110 reviewed
Sorry did not see that my comments were saved in a "review" and not applied directly...

2022-12-18 10:36 UTC, Lemongrass3110 approved these changes

2022-12-19 02:36 UTC, aleos89 approved these changes

2022-12-19 11:19 UTC, merged