Corrected script for some item #16
rathena/rathena pull request #7583
Opened 2023-02-07 07:19 UTC by idk-whoami

* **Addressed Issue(s)**: 

* **Server Mode**: re

* **Description of Pull Request**: Implementations + corrections of a bunch of items

2023-02-11 14:21 UTC, Atemo requested changes

2023-02-11 15:46 UTC, idk-whoami commented on db/re/item_combos.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer))) {
Thanks!

2023-02-11 15:46 UTC, idk-whoami commented on db/re/item_combos.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer)))
Thanks!

2023-02-11 15:46 UTC, idk-whoami commented on db/re/item_combos.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer))) {
Thanks!

2023-02-11 15:46 UTC, idk-whoami commented on db/re/item_combos.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer))) {
Thanks!

2023-02-11 15:46 UTC, idk-whoami commented on db/re/item_combos.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer)))
Thanks!

2023-02-11 15:47 UTC, idk-whoami commented on db/re/item_combos.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer)))
Thanks!

2023-02-11 15:47 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer))) {
Thanks!

2023-02-11 15:47 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer))) {
Thanks!

2023-02-11 15:47 UTC, idk-whoami commented on db/re/item_db_equip.yml
> +      if ((eaclass()&EAJL_THIRD && BaseJob == Job_Bard) || ((eaclass()&EAJL_THIRD && BaseJob == Job_Dancer))) {
Thanks!

2023-02-12 14:33 UTC, merged

2023-02-12 14:33 UTC, Atemo commented
Thanks again <3