Fix some items' names for Alberta stylish npc
rathena/rathena pull request #7666
Opened 2023-03-27 02:28 UTC by austin-sa-wang

NPC: `'Bao Bao', 'Crescent Hairpin', 'Fashionable Glasses', 'Heart Hairpin' Quest`

Fixed names to match db's english name

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

2023-03-27 03:11 UTC, secretdataz requested changes
Looks good overall.

2023-03-27 03:11 UTC, secretdataz commented on npc/quests/quests_alberta.txt
> +							delitem 4052,1; //Elder_Willow_Card
This is AegisName reference which contains the typo.

2023-03-27 03:11 UTC, secretdataz commented on npc/quests/quests_alberta.txt
> +			mes "1 ^0000FFHeart hairpin^000000";
```suggestion
			mes "1 ^0000FFHeart Hairpin^000000";
```

2023-04-08 10:05 UTC, Lemongrass3110 approved these changes

2023-04-08 10:05 UTC, Lemongrass3110 commented on npc/quests/quests_alberta.txt
> +							delitem 4052,1; //Elder_Willow_Card
```suggestion
							delitem 4052,1; //Elder_Wilow_Card
```

2023-04-08 12:39 UTC, merged