Fix Illusion of Underwater
rathena/rathena pull request #7800
Opened 2023-06-02 23:28 UTC by mazvi

Temp fix Illusion of Underwater because prt_elib is not implemented yet

* **Addressed Issue(s)**: N/A

* **Server Mode**: RENEWAL

* **Description of Pull Request**:

2023-06-03 00:17 UTC, Atemo commented
> prt_elib is not implemented yet

If you mean the warps, add them
```
prt_elib,14,46,0	warp2	Libraryo	10,10,prontera,192,264
prontera,192,267,0	warp2	Libraryi	2,2,prt_elib,18,46
```

2023-06-03 00:35 UTC, mazvi commented
> > prt_elib is not implemented yet
> 
> If you mean the warps, add them
> 
> ```
> prt_elib,14,46,0	warp2	Libraryo	1,2,prontera,192,264
> prontera,192,267,0	warp2	Libraryi	2,2,prt_elib,18,46
> ```

The rathena default packet now is 20211103 this is not support prt_lib

2023-06-03 13:03 UTC, Atemo requested changes
We can leave the old coordinates commented if you want.
Although the default packet is 2021, the server can support newer clients. As such there is no point to change the map in the script.

2023-06-03 13:16 UTC, mazvi commented
Okay :)

2023-06-04 14:52 UTC, mazvi commented
> We can leave the old coordinates commented if you want. Although the default packet is 2021, the server can support newer clients. As such there is no point to change the map in the script.

After I thought about it, the things I made earlier were good because all NPCs like books and library girls were still in prt_in not prt_elib.

2023-06-04 16:26 UTC, OptimusM commented
To be honest, i think the best for now it is leave it on the old prontera library, since new prt lib has alot more npc's, also a bunch of instances related to Fantasy VR books, so, don't think rA will develop that on some near future, because yeah, those are mostly "lore content" and not really important stuff.

2023-06-04 18:55 UTC, Atemo commented
The goal is to be as close as possible to the original content. The project is configurable enough to allow you to modify the npcs in your server to your liking.

2023-06-04 18:56 UTC, merged