Added illusion Merchant
rathena/rathena pull request #7854
Opened 2023-07-24 13:14 UTC by Haydrich

> * **Addressed Issue(s)**:
> * **Server Mode**: Renewal
> * **Description of Pull Request**:
Added Illusion Merchant

- [ ] NPC Shop Update Day
- [ ] English Translation

2023-07-25 13:02 UTC, Atemo commented on npc/re/merchants/enchan_illusion_dungeons.txt
> +	setunitdata .@npc_id,UNPC_CLASS,2;
```suggestion
	setunitdata .@npc_id,UNPC_CLASS,4003;	// MAGICIAN_H
```

2023-09-03 21:42 UTC, Lemongrass3110 requested changes

2023-09-03 21:42 UTC, Lemongrass3110 commented on npc/re/merchants/enchan_illusion_dungeons.txt
> +	setunitdata .@npc_id,UNPC_CLASS,4003;	// MAGICIAN_H
```suggestion
	setunitdata .@npc_id,UNPC_CLASS, JOB_MAGE_HIGH;
```

2023-09-03 21:42 UTC, Lemongrass3110 commented on npc/re/merchants/enchan_illusion_dungeons.txt
> +	setunitdata .@npc_id,UNPC_SEX,2;
Please use the constant SEX_FEMALE (0) or SEX_MALE (1).

2023-09-03 21:42 UTC, Lemongrass3110 commented on npc/re/merchants/enchan_illusion_dungeons.txt
> +// prontera,88,113,5	script	Illusion Merchant#0829	MAGICIAN_H,{
```suggestion

```

2023-09-03 21:42 UTC, Lemongrass3110 commented on npc/re/merchants/enchan_illusion_dungeons.txt
> +		mes "[Illusion Merchant]";
Its really strange that our script engine supports this, but please dont use this kind of syntax.

2023-09-03 21:44 UTC, Lemongrass3110 commented
As for the shop update / market restock:
We have confirmed a few times already, that AEGIS does not persist the markets and this was a custom implementation by previous developers of rAthena or Hercules.
In reality AEGIS simply refills on each restart and because they have a fixed schedule for restarting it looks like a "refill" on a specific day.

2023-09-14 20:50 UTC, Atemo approved these changes

2023-09-14 22:30 UTC, aleos89 approved these changes

2023-09-21 14:11 UTC, Atemo approved these changes

2024-01-17 13:35 UTC, Atemo approved these changes

2024-01-17 13:35 UTC, Atemo commented on npc/re/merchants/barters/enchan_illusion_dungeons.yml
> +            Amount: 150
```suggestion
            Amount: 150

```

2024-01-17 22:11 UTC, Atemo commented on npc/re/merchants/enchan_illusion_dungeons.txt
> +	setunitdata .@npc_id,UNPC_HAIRCOLOR,2;
```suggestion
	setunitdata .@npc_id,UNPC_HAIRCOLOR,2;

	// Restock
	npcshopupdate "market_resonance_stone",100003,2000000,99999;
	npcshopupdate "market_resonance_stone",100004,2000000,99999;
```

2024-01-18 19:30 UTC, Lemongrass3110 approved these changes

2024-01-18 19:31 UTC, merged