Do not exit the process while receiving crash signal so that the syst…
rathena/rathena pull request #7902
Opened 2023-08-21 02:57 UTC by inhyositsu

…em will make core dump correctly in Linux.

* **Addressed Issue(s)**: None.

* **Server Mode**: Both

* **Description of Pull Request**: Fix the problem that server won't make core dump when crashing in Linux environments.

2023-08-21 13:05 UTC, aleos89 approved these changes

2023-08-27 14:38 UTC, Lemongrass3110 requested changes

2023-08-27 14:38 UTC, Lemongrass3110 commented on src/common/core.cpp
> +#endif
```suggestion
```

Should be removed on all OS.
Was mistakenly introduced by me in #7303

2023-08-27 17:43 UTC, Lemongrass3110 approved these changes

2023-08-27 23:14 UTC, merged