Algorithm for opening group items in renewal
rathena/rathena pull request #8849
Opened 2024-11-24 12:04 UTC by Playtester

* **Addressed Issue(s)**: #8848 

* **Server Mode**: Renewal

**Description of Pull Request**: 

- SubGroup 1-5 now use a new algorithm where rate is the amount of items in the group
  * When an item is retrieved from the group, it is removed from the group
  * Only when the group is completely empty or the server restarts, the group refills
  * This will only take effect when you use the command "getgroupitem"
  * Using "getrandgroupitem" or SubGroup 6 will still return a fully random item based on rate
- Battle config "item_group_rate" now only applies to GROUP_SEARCH_DROP
  * This is accomplished by storing the adjusted rate in a separate variable
- Fixes #8848 

Hint: We also need to update the documentation of these commands, I will do that once the current implementation was approved.

2024-11-24 20:55 UTC, secretdataz requested changes
I don't like this implementation where assigning items to subgroup 6 implicitly assigns a different random algorithm (imitating aegis).  Please make an YAML database attribute that makes algorithm for each subgroup customizable.

```yaml
- Group: SOME_BOX
    SubGroups:
      - SubGroup: 1
        Algorithm: Random
        List:
             # ....
      - SubGroup: 2
        Algorithm: NaturalRandom
        List:
             # ....
```

2024-12-04 17:02 UTC, Playtester commented on src/tool/yamlupgrade.cpp
> +						body << YAML::Key << "Algorithm" << YAML::Value << "NaturalRandom";
This doesn't seem to match with the syntax you defined in the files.

2024-12-04 17:05 UTC, Playtester commented on src/map/itemdb.hpp
> +	GROUP_DRAWS_DROP, // Draws with replacement. Pick one item from the group and check use rate as drop rate, on fail, do not return any item
I still suggest replacing the descriptions here.

2024-12-04 17:07 UTC, Playtester commented on src/map/itemdb.cpp
> +				this->pc_get_itemgroup_sub( sd, identify, this->get_random_itemsubgroup( random.second, GROUP_DRAWS_REPLACEMENT ) );
Could have both cases together in one and just give random.second->draws into the function.

2024-12-04 17:08 UTC, Playtester commented on src/map/itemdb.cpp
> +	std::shared_ptr<s_item_group_db> group = this->find(group_id);
As mentioned before I'm again duplicating all this code. It should just be one function or one function calls the other.

But the problem here is also that you're changing how getrandgroupitem works as discussed on Discord.

2024-12-04 18:29 UTC, Playtester commented on db/pre-re/item_group_db.yml
> +        Draws: NoReplacement
All pre-re groups should use true random so it should be "Replacement" here, right? Maybe I'm still misunderstanding the definition of these fields, but to me calling the algorithm that always have the same chances "NoReplacement" and calling the algorithm that actually removes the items without replacing them "Replacement" seems like the opposite of what your intent was.

2024-12-14 15:47 UTC, Atemo approved these changes

2024-12-17 11:33 UTC, secretdataz approved these changes
lgtm

2024-12-17 17:26 UTC, merged